---
forum_app_dir: "{{ app_dir }}/forum"
forum_code_dir: "{{ forum_app_dir }}/cs_comments_service"
forum_data_dir: "{{ data_dir }}/forum"
forum_rbenv_dir: "{{ forum_app_dir }}"
forum_rbenv_root: "{{ forum_app_dir }}/.rbenv"
forum_rbenv_shims: "{{ forum_rbenv_root }}/shims"
forum_rbenv_bin: "{{ forum_rbenv_root }}/bin"
forum_gem_root: "{{ forum_rbenv_dir }}/.gem"
forum_gem_bin: "{{ forum_gem_root }}/bin"
forum_path: "{{ forum_code_dir }}/bin:{{ forum_rbenv_bin }}:{{ forum_rbenv_shims }}:{{ forum_gem_bin }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

forum_environment:
  RBENV_ROOT: $forum_rbenv_root
  GEM_HOME: $forum_gem_root
  PATH: $forum_path

forum_user: "forum"
forum_ruby_version: "1.9.3-p448"
forum_source_repo: "https://github.com/edx/cs_comments_service.git"
forum_version: "HEAD"
forum_mongo_user: "cs_comments_service"
forum_mongo_password: "password"
forum_mongo_host: "localhost"
forum_mongo_port: "27010"
forum_mongo_database: "cs_comments_service"
forum_mongo_url: "mongodb://{{ forum_mongo_user }}:{{ forum_mongo_password }}@{{ forum_mongo_host }}:{{ forum_mongo_port }}/{{ forum_mongo_database }}"
forum_rack_env: "development"
forum_sinatra_env: "development"
forum_api_key: "password"
forum_elasticsearch_host: "localhost"
forum_elasticsearch_port: "9200"
forum_elasticsearch_url: "http://{{ forum_elasticsearch_host }}:{{ forum_elasticsearch_port }}"

#
# test config
#

#
# The following services should be listening on the associated
# ports when the role has been successfully created.
#
forum_services:
  - {service: "sinatra", host: "localhost", port: "4567"}
  - {service: "mongo", host: "{{ forum_mongo_host  }}", port: "27017"}
  - {service: "mongo", host: "{{ forum_mongo_host }}", port: "28017"}
  - {service: "elasticsearch", host: "{{ forum_elasticsearch_host }}", port: "9200"}
  - {service: "elasticsearch", host: "{{ forum_elasticsearch_host }}", port: "9300"}
