---
- name: Creating admin users
  user: name={{ item.user }} groups={{ ",".join(item.groups) }}
  sudo: True
  with_items: admin_users
- name: Copying ssh keys for admin users
  authorized_key: user={{ item.user }} key="{{ lookup('file', item.path) }}"
  sudo: True
  with_items: admin_keys
- name: Creating env users
  user: name={{ item.user }} groups={{ ",".join(item.groups) }}
  sudo: True
  with_items: env_users
- name: Copying ssh keys for env users
  authorized_key: user={{ item.user }} key="{{ lookup('file', item.path) }}"
  sudo: True
  with_items: env_keys
