---
- name: common | Add user www-data
  # This is the default user for nginx
  user: name=www-data

- name: common | Create common directories
  file: >
    path={{ data_dir }}
    state=directory
    owner=root
    group=root
    mode=0755
  with_items:
    - "{{ data_dir }}"
    - "{{ app_dir }}"
    - "{{ log_dir }}"

- name: common | Install role-independent useful system packages
  # do this before log dir setup; rsyslog package guarantees syslog user present
  apt: pkg={{','.join(common_debian_pkgs)}} install_recommends=yes state=present update_cache=yes
  tags:
  - pre_install
  - update
  - update

- name: common | upload sudo config for key forwarding as root
  copy: src=ssh_key_forward dest=/etc/sudoers.d/ssh_key_forward validate='visudo -c -f %s' owner=root group=root mode=0440

- name: common | pip install virtualenv
  pip: >
    name="{{ item }}"
    state=present
    extra_args="-i {{ PYPI_MIRROR_URL }}"
  with_items: common_pip_pkgs

- name: common | Install rsyslog configuration for edX
  template: dest=/etc/rsyslog.d/99-edx.conf src=edx_rsyslog.j2 owner=root group=root mode=644
  notify: common | restart rsyslogd
  tags:
  - logging
  - update
  notify: common | restart rsyslogd

- name: common | Install logrotate configuration for edX
  template: dest=/etc/logrotate.d/edx-services src=edx_logrotate.j2 owner=root group=root mode=644
  tags:
  - logging
  - update
  notify: common | restart logrotate


- name: common | Install logrotate configuration for tracking file
  template: dest=/etc/logrotate.d/tracking.log src=edx_logrotate_tracking_log.j2 owner=root group=root mode=644
  tags:
  - logging
  - update
  notify: common | restart logrotate
