---
- include: create_users.yml
- name: Create application root
  sudo: True
  action: file path=/opt/wwc state=directory owner=root group=root
- name: Create log directory
  sudo: True
  action: file path=/mnt/logs state=directory
