---
- include: create_users.yml
- name: Create application root
  sudo: True
  file: path=$app_base_dir state=directory owner=root group=root
- name: Create log directory
  sudo: True
  file: path=/mnt/logs state=directory
- name: Fix EC2 packages in VPC
  sudo: True
  command: sed -i -e 's/us-west-2.ec2/us/' /etc/apt/sources.list
- name: Update apt cache
  sudo: True
  apt: update_cache=yes
