---
- include: create_users.yml
- name: Create application root
  sudo: True
  file: path=$app_base_dir state=directory owner=root group=root
- name: Create ruby base
  sudo: True
  file: path=$ruby_base state=directory owner=www group=www
- name: Create log directory
  sudo: True
  file: path=/mnt/logs state=directory
- name: Update apt cache
  sudo: True
  apt: update_cache=yes
