mongo_dbpath: /var/lib/mongodb
mongo_logpath: /var/log/mongodb/mongodb.log
mongo_logappend: true
mongo_bind_ip: 127.0.0.1
mongo_extra_conf: ''

MONGO_USERS:
  - user: cs_comments_service
    password: password
    database: cs_comments_service
  - user: exdapp
    password: password
    database: edxapp
