---
#Upload config files for django (auth and env)
- name: discern | create discern application config env.json file
  template: src=env.json.j2 dest={{app_dir}}/env.json
  sudo_user: "{{ discern_user }}"
  notify:
    - discern | restart celery
    - discern | restart discern

- name: discern | create discern auth file auth.json
  template: src=auth.json.j2 dest={{app_dir}}/auth.json
  sudo_user: "{{ discern_user }}"
  notify:
    - discern | restart celery
    - discern | restart discern

#Needed if using redis to prevent memory issues
- name: discern | change memory commit settings -- needed for redis
  command: sysctl vm.overcommit_memory=1

- name: discern | set permissions on app_dir sgid for edx
  file: path={{app_dir}} owner=root group=edx mode=2775 state=directory
  file: path={{venv_dir}} owner=root group=edx mode=2775 state=directory

#Grab both repos or update
- name: discern | git checkout discern repo into discern_dir
  git: dest={{discern_dir}} repo={{discern_source_repo}} version={{discern_branch}}
  sudo_user: "{{ discern_user }}"
  notify:
    - discern | restart celery
    - discern | restart discern

- name: discern | git checkout ease repo into ease_dir
  git: dest={{ease_dir}} repo={{ease_source_repo}} version={{ease_branch}}
  sudo_user: "{{ discern_user }}"
  notify:
    - discern | restart celery
    - discern | restart discern

#Numpy has to be a pre-requirement in order for scipy to build
- name : install python pre-requirements for discern and ease
  pip: requirements="{{item}}/pre-requirements.txt" virtualenv="{{ discern_venv_dir }}" state=present
  sudo_user: "{{ discern_user }}"
  with_items:
    - "{{ discern_pre_requirements_file }}"
    - "{{ discern_ease_pre_requirements_file }}"

- name : install python requirements for discern and ease
  pip: requirements="{{item}}/requirements.txt" virtualenv="{{ discern_venv_dir }}" state=present
  sudo_user: "{{ discern_user }}"
  with_items:
    - "{{ discern_post_requirements_file }}"
    - "{{ discern_ease_post_requirements_file }}"

- name: discern | install ease python package
  shell: command="{{discern_venv_dir}}/bin/activate; cd {{ discern_ease_code_dir }}; python setup.py install"

#Needed for the ease package to work
- name: discern | install nltk data using rendered shell script
  shell: command="{{ discern_venv_dir }}/bin/python -m nltk.downloader -d {{ discern_nltk_data_dir }} all"
  sudo_user: "{{ discern_user }}"

#Run this instead of using the ansible module because the ansible module only support syncdb of these three, and does not
#support virtualenvs as of this comment
- name: discern | django syncdb, migrate, and collectstatic for discern
  shell: "{{ discern_venv_dir }}/bin/python {{discern_code_dir}}/manage.py {{item}} --noinput --settings={{discern_settings}} --pythonpath={{discern_code_dir}}"
  sudo_user: "{{ discern_user }}"
  with_items:
    - syncdb
    - migrate
    - collectstatic

#Have this separate from the other three because it doesn't take the noinput flag
- name: discern | django update_index for discern
  shell: "{{ discern_venv_dir}}/bin/python {{discern_code_dir}}/manage.py update_index --settings={{discern_settings}} --pythonpath={{discern_code_dir}}"
  sudo_user: "{{ discern_user }}"
