---
- name: discern | create application user
  user: >
    name="{{ discern_user }}"
    home="{{ discern_app_dir }}"
    createhome=no
    shell=/bin/false

- name: discern | create discern app and data dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ discern_user }}"
    group="{{ common_web_group }}"
  with_items:
    - "{{ discern_app_dir }}"
    - "{{ discern_data_dir }}"
    - "{{ discern_venvs_dir }}"

- name: discern | install debian packages that discern needs
  apt: pkg={{ item }} state=present
  with_items: discern_debian_pkgs

- name: discern | install debian packages for ease that discern needs
  apt: pkg={{ item }} state=present
  with_items: discern_ease_debian_pkgs

- name: discern | render celery service from template
  template: >
    src=celery.conf.j2 dest=/etc/init/celery.conf
    owner=root group=root
  notify: discern | restart celery

- name: discern | render discern service from template
  template: >
    src=discern.conf.j2 dest=/etc/init/discern.conf
    owner=root group=root
  notify: discern | restart discern

- name: discern | copy sudoers file for discern
  copy: >
    src=sudoers-discern dest=/etc/sudoers.d/discern
    mode=0440 validate='visudo -cf %s' owner=root group=root

#Needed if using redis to prevent memory issues
- name: discern | change memory commit settings -- needed for redis
  command: sysctl vm.overcommit_memory=1

- include: deploy.yml

- name: discern | create a symlink for venv python
  file: >
    src="{{ discern_venv_bin }}/python"
    dest={{ COMMON_BIN_DIR }}/python.discern
    state=link
