---
- name: update sudoers file with template
  template: src=sudoers.j2 dest=/etc/sudoers owner=root group=root mode=0440

- name: stop all services
  service: name={{item}} state=stopped
  with_items:
    - celery
    - nginx
    - discern

#Upload config files for django (auth and env)
- name: create discern application config env.json file
  template: src=env.json.j2 dest=$app_base_dir/env.json owner={{remote_user}} group=edx mode=0640

- name: create discern auth file auth.json
  template: src=auth.json.j2 dest=$app_base_dir/auth.json owner={{remote_user}} group=edx mode=0640

#Needed if using redis to prevent memory issues
- name: change memory commit settings -- needed for redis
  command: sysctl vm.overcommit_memory=1

#Needed to pull repos from github, due to hanging on host add prompt otherwise
- name: add github to the known hosts file
  shell: ssh-keyscan -H github.com > ~/.ssh/known_hosts

- name: set permissions on $app_base_dir sgid for edx
  file: path=$app_base_dir owner={{remote_user}} group=edx mode=2775 state=directory
  file: path={{venv_dir}} owner={{remote_user}} group=edx mode=2775 state=directory

- name: Install git so that we can clone repos
  apt: pkg=git install_recommends=yes state=present

#Create directories for repos
- name: create discern and ease directories and set permissions
  file: path={{item}} owner={{remote_user}} group=edx mode=2775 state=directory
  with_items:
   - ${discern_dir}
   - ${ease_dir}

#Grab both repos or update
- name: git checkout discern repo into discern_dir
  git: dest={{discern_dir}} repo={{discern_source_repo}} version={{discern_branch}}

- name: git checkout ease repo into ease_dir
  git: dest={{ease_dir}} repo={{ease_source_repo}} version={{ease_branch}}

#Install system packages
- name: install discern and ease apt packages
  command: xargs -a {{item}}/apt-packages.txt apt-get install -y
  with_items:
    - ${discern_dir}
    - ${ease_dir}

#Numpy has to be a pre-requirement in order for scipy to build
- name : install python pre-requirements for discern and ease
  pip: requirements="{{item}}/pre-requirements.txt" virtualenv="{{venv_dir}}" state=present
  with_items:
    - ${discern_dir}
    - ${ease_dir}

- name : install python requirements for discern and ease
  pip: requirements="{{item}}/requirements.txt" virtualenv="{{venv_dir}}" state=present
  with_items:
    - ${discern_dir}
    - ${ease_dir}

- name: install ease python package
  shell: command="{{venv_dir}}/bin/activate; cd {{ease_dir}}; python setup.py install"

#Needed for the ease package to work
- name: install nltk data using rendered shell script
  shell: command="{{venv_dir}}/bin/python -m nltk.downloader -d {{nltk_data_dir}} all"

- name: set permissions on nltk data directory
  file: path={{nltk_data_dir}} owner={{remote_user}} group=edx mode=2775 state=directory

#Run this instead of using the ansible module because the ansible module only support syncdb of these three, and does not
#support virtualenvs as of this comment
- name: django syncdb, migrate, and collectstatic for discern
  shell: ${venv_dir}/bin/python {{discern_dir}}/manage.py {{item}} --noinput --settings={{discern_settings}} --pythonpath={{discern_dir}}
  with_items:
    - syncdb
    - migrate
    - collectstatic

#Have this separate from the other three because it doesn't take the noinput flag
- name: django update_index for discern
  shell: ${venv_dir}/bin/python {{discern_dir}}/manage.py update_index --settings={{discern_settings}} --pythonpath={{discern_dir}}

#Create the templates for upstart services
- name: render celery service from template
  template: src=celery.conf.j2 dest=/etc/init/celery.conf

- name: render discern service from template
  template: src=discern.conf.j2 dest=/etc/init/discern.conf

- name: create nginx directory and set perms
  file: path=/etc/nginx/sites-available owner=root group=edx mode=2775 state=directory

- name: render nginx sites available
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: start all services
  service: name={{item}} state=started
  with_items:
    - celery
    - nginx
    - discern