---
- name: gh_mirror | create gh_mirror user
  user: >
    name={{ gh_mirror_user }}
    state=present

- name: gh_mirror | create the gh_mirror data directory
  file: >
    path={{ gh_mirror_data_dir }}
    state=directory
    owner={{ gh_mirror_user }}
    group={{ gh_mirror_group }}

- name: gh_mirror | create the gh_mirror app directory
  file: >
    path={{ gh_mirror_app_dir }}
    state=directory

- name: gh_mirror | create org config
  template: src=orgs.yml.j2 dest={{ gh_mirror_app_dir }}/orgs.yml

- name: copying sync scripts
  copy: src={{ item }} dest={{ gh_mirror_app_dir }}/{{ item }}
  with_items: "{{ gh_mirror_app_files }}"
