---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
# Tasks for role edx_ansible
#
# Overview:
#
# This is an edx_ansible role that installs edx_ansible :)
# The purpose is to install edx_ansible on a server so
# that it can be updated locally.
#
# This role will also drop some helper scripts that
# for running edx_ansible tasks
#
# Example play:
#
#
#
- name: edx_ansible | create application user
  user: >
    name="{{ edx_ansible_user }}"
    home="{{ edx_ansible_app_dir }}"
    createhome=no
    shell=/bin/false

- name: edx_ansible | create edx_ansible app and venv dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ edx_ansible_user }}"
    group="{{ common_web_group }}"
  with_items:
    - "{{ edx_ansible_app_dir }}"
    - "{{ edx_ansible_venvs_dir }}"

- name: edx_ansible | install a bunch of system packages on which edx_ansible relies
  apt: pkg={{','.join(edx_ansible_debian_pkgs)}} state=present

- name: edx_ansible | git checkout edx_ansible repo into edx_ansible_code_dir
  git: dest={{ edx_ansible_code_dir }} repo={{ edx_ansible_source_repo }} version={{ edx_ansible_version }}
  sudo_user: "{{ edx_ansible_user }}"

- name : edx_ansible | install edx_ansible venv requirements
  pip: requirements="{{ edx_ansible_requirements_file }}" virtualenv="{{ edx_ansible_venv_dir }}" state=present
  sudo_user: "{{ edx_ansible_user }}"

- name: edx_ansible | create update script
  template: >
    dest={{ edx_ansible_app_dir}}/update
    src=update owner=edx_ansible group=edx_ansible mode=755

- name: edxapp | create a symlink for update.sh
  file: >
    src={{ edx_ansible_app_dir }}/update
    dest={{ COMMON_BIN_DIR }}/update
    state=link
