- name: supervisor | restart supervisor
  service: >
    name={{ supervisor_service }}
    state=restarted

- name: supervisor | reload supervisor
  shell: "{{ supervisor_ctl }} -c {{ supervisor_cfg }} reload"
