# Variables for all common playbook
#
# If a new variable is added please document it!
---
nginx_cfg:
  #   - link - turn on
  #   - absent - turn off 
  sites_enabled:
    basic_auth: link
    edx_release: link
  # path to version files for the basic
  # nginx configuration
  version_html: /opt/wwc/versions.html
  version_json: /opt/wwc/versions.json
  # default htpasswd contents set to edx/edx
  # this value can be overiden in vars/secure/<group>.yml
  htpasswd: |
    edx:$apr1$2gWcIvlc$Nu7b/KTwd5HoIDEkSPNUk/

