#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role devpi
#
# Overview:
#   Creates a pypi caching server
#
# Dependencies:
#   - common
#   - nginx
#   - supervisor
#
# Example play:
#   roles:
#     - common
#     - role: nginx
#       nginx_sites:
#       - devpi
#     - role: supervisor
#       supervisor_servers:
#       - devpi
#     - devpi

---
- name: devpi | create devpi user
  user: >
    name={{ devpi_user }}
    home={{ devpi_app_dir }}
    shell=/bin/false createhome=no

- name: devpi | create virtualenv directory
  file: >
    path={{ devpi_venv_dir }}
    state=directory
    owner={{ devpi_user }}
    group={{ devpi_group }}
  notify: devpi | restart devpi

- name: devpi | create the devpi data directory
  file: >
    path={{ devpi_data_dir }}
    state=directory
    owner={{ common_web_user }}
    group={{ devpi_group }}

- name: devpi | install devpi pip pkgs
  pip: >
    name={{ item }}
    state=present
    virtualenv={{ devpi_venv_dir }}
  sudo_user: "{{ devpi_user }}"
  with_items: devpi_pip_pkgs
  notify: devpi | restart devpi

- name: devpi | writing supervisor script
  template: >
    src=devpi.conf.j2 dest={{ supervisor_cfg_dir }}/devpi.conf
    owner={{ supervisor_user }} group={{ common_web_user }} mode=0644
  notify: devpi | restart devpi

- name: devpi | create a symlink for venv python
  file: >
    src="{{ devpi_venv_bin }}/{{ item }}"
    dest={{ COMMON_BIN_DIR }}/{{ item }}.devpi
    state=link
  with_items:
  - python
  - pip

# flush queued up handlers so that devpi
# is restarted since downstream roles
# will need to use it
- meta: flush_handlers
