- name: check for elasticsearch
  command: test -f /var/tmp/elasticsearch-${elastic_search_version}.deb
  ignore_errors: true
  register: es_present

- name: download elasticsearch
  get_url: url={{ elastic_search_url }} dest=/var/tmp/{{ elastic_search_file }}
  when: es_present|failed
  tags:
    - elasticsearch
    - install

- name: install elasticsearch from local package
  shell: executable=/bin/bash dpkg -i /var/tmp/elasticsearch-${elastic_search_version}.deb
  when: es_present:failed
  tags:
    - elasticsearch
    - install
