- name:  elasticsearch | check for elasticsearch
  command: test -f /var/tmp/elasticsearch-${elasticsearch_version}.deb
  ignore_errors: true
  register: es_present

- name:  elasticsearch | download elasticsearch
  get_url: url={{ elasticsearch_url }} dest=/var/tmp/{{ elasticsearch_file }}
  when: es_present|failed
  tags:
    - elasticsearch
    - install

- name:  elasticsearch | check elasticsearch version
  command: 'curl -s -XGET localhost:9200'
  register: elasticsearch_running_version

- name: elasticsearch | debug
  debug: msg="Debuging {{ elasticsearch_running_version }}"

- name: elasticsearch | parse
  datagrabber: data='{"ok":true}'
  register: foo_bar

- name: elasticsearch | debug2
  debug: msg="$foo_bar.ok"

- name: elasticsearch | install elasticsearch from local package
  shell: executable=/bin/bash dpkg -i /var/tmp/elasticsearch-${elasticsearch_version}.deb
  only_if: "{{ elasticsearch_running_version }} != {{ elasticsearch_version }}" 
  tags:
    - elasticsearch
    - install
