---

notifier_user: "notifier"
notifier_home: "/opt/wwc/notifier"
notifier_venv_dir: "{{ notifier_home }}/virtualenvs/notifier"
notifier_source_repo: "git@github.com:edx/notifier.git"
notifier_code_dir: "{{ notifier_home }}/src"
notifier_version: "preintegration"
notifier_git_identity_path: "{{ secure_dir }}/files/git-identity"
notifier_requirements_file: "{{ notifier_code_dir }}/requirements.txt"

notifier_env: "Development"

notifier_email_host: "localhost"
notifier_email_port: 25
notifier_email_user: ""
notifier_email_pass: ""
notifier_email_host: ""


notifier_email_domain: "notifications.edx.org"
notifier_email_rewrite_recipient: ""

notifier_lms_url_base: "http://localhost:8000"

notifier_comment_service_base: "http://localhost:4567"
2notifier_comment_service_api_key: "PUT_YOUR_API_KEY_HERE"

notifier_user_service_base: "http://localhost:8000"
notifier_user_service_api_key: "PUT_YOUR_API_KEY_HERE"

notifier_celery_broker_url: "django://"


notifier_debian_pkgs:
  - apparmor-utils
  - build-essential
  - curl
  - g++
  - gcc
  - ipython
  - pkg-config
  - rsyslog