#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role supervisor
#
# Overview:
#   Role for supervisord
#   Installs supervisor in its own venv.
#
# Dependencies:
#   - common
#
# Example play:
#   roles:
#     - common
#     - role: supervisor

---
- name: supervisor | create application user
  user: >
    name="{{ supervisor_user }}"
    home="{{ supervisor_app_dir }}"
    createhome=no
    shell=/bin/false

- name: supervisor | create supervisor directories
  file: >
    name={{ item }}
    state=directory
    owner={{ supervisor_user }}
    group={{ common_web_user }}
  with_items:
    - "{{ supervisor_app_dir }}"
    - "{{ supervisor_venvs_dir }}"

- name: supervisor | create supervisor directories
  file: >
    name={{ item }}
    state=directory
    owner={{ common_web_user }}
    group={{ supervisor_user }}
  with_items:
    - "{{ supervisor_cfg_dir }}"
    - "{{ supervisor_data_dir }}"
    - "{{ supervisor_log_dir }}"


- name: supervisor | install supervisor in its venv
  pip: name=supervisor virtualenv="{{supervisor_venv_dir}}" state=present
  sudo_user: "{{ supervisor_user }}"
  notify: supervisor | restart supervisor

- name: supervisor | create supervisor upstart job
  template: >
    src=supervisor-upstart.conf.j2 dest=/etc/init/supervisor.conf
    owner=root group=root
  notify: supervisor | restart supervisor

- name: supervisor | create supervisor master config
  template: >
    src=supervisord.conf.j2 dest={{ supervisor_cfg }}
    owner={{ supervisor_user }} group={{ common_web_user }}
    mode=0644
  notify: supervisor | restart supervisor

- name: supervisor | create a symlink for supervisortctl
  file: >
    src={{ supervisor_ctl }}
    dest={{ COMMON_BIN_DIR }}/{{ supervisor_ctl|basename }}
    state=link

- name: supervisor | create a symlink for supervisor cfg
  file: >
    src={{ supervisor_cfg }}
    dest={{ COMMON_CFG_DIR }}/{{ supervisor_cfg|basename }}
    state=link

- name: supervisor | create a symlink for supervisor cfg dir
  file: >
    src={{ supervisor_cfg_dir }}
    dest={{ COMMON_CFG_DIR }}/supervisor.{{ supervisor_cfg_dir|basename }}
    state=link


- name: supervisor | ensure supervisor is started
  service: name=supervisor state=started
