- name: stop xqueue
  service: name=xqueue state=stopped
  ignore_errors: yes
  tags:
  - xqueue
  - deploy

- name: start xqueue
  service: name=xqueue state=started
  tags:
  - xqueue
  - deploy

- name: restart xqueue
  service: name=xqueue state=restarted
  tags:
  - xqueue
  - deploy
