- name: Deploy common
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    enable_datadog: True
    enable_newrelic: True
  vars_files:
    - ["{{ secure_vars }}", "dummy.yml"]
  roles:
    - common
    - role: datadog
      when: enable_datadog
    - role: newrelic
      when: enable_newrelic
