- hosts: tag_aws_cloudformation_stack-name_continuous-integration:&tag_group_edxapp
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_continuous_integration_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
  roles:
    - common
    - nginx
    - gunicorn
    - edxapp
    - ruby
    - npm
