# This is a utility play to initialize the mysql dbs for the following
# roles:
#   - edxapp
#   - xqueue
#   - ora
#   - discern
#
# The mysql root user MUST be passed in as extra vars for
# at least one of the databases.
#
# the environment and deployment must be passed in as COMMON_ENVIRONMENT
# and COMMON_DEPLOYMENT.  These two vars should be set in the secret
# var file for the corresponding vpc stack
#
# Example invocation:
#
# Create the databases for edxapp and xqueue:
#
# ansible-playbook -i localhost, create_db_users.yml -e@/path/to/secrets.yml -e "edxapp_db_root_user=root xqueue_db_root_user=root"
#
#
- name: Create all databases on the edX stack
  hosts: all
  gather_facts: False
  vars:
    # These should be set to the root user for the
    # db, if left 'None' the databse will be skipped
    edxapp_db_root_user: 'None'
    xqueue_db_root_user: 'None'
    ora_db_root_user: 'None'
    discern_db_root_user: 'None'

  vars_prompt:
    # passwords use vars_prompt so they aren't in the
    # bash history
    - name: "edxapp_db_root_pass"
      prompt: "Password for edxapp root mysql user (enter to skip)"
      default: "None"
      private: yes
    - name: "xqueue_db_root_pass"
      prompt: "Password for xqueue root mysql user (enter to skip)"
      default: "None"
      private: yes
    - name: "ora_db_root_pass"
      prompt: "Password for ora root mysql user (enter to skip)"
      default: "None"
      private: yes
    - name: "discern_db_root_pass"
      prompt: "Password for discern root mysql user (enter to skip)"
      default: "None"
      private: yes


  tasks:
    - fail: msg="COMMON_ENVIRONMENT and COMMON_DEPLOYMENT need to be defined to use this play"
      when: COMMON_ENVIRONMENT is not defined or COMMON_DEPLOYMENT is not defined
    - name: create mysql databases for the edX stack
      mysql_db: >
        db={{ item[0] }}{{ item[1].db_name }}
        state=present
        login_host={{ item[1].db_host }}
        login_user={{ item[1].db_user }}
        login_password={{ item[1].db_pass }}
        encoding=utf8
      when: item[1].db_user != 'None'
      with_nested:
        - ['{{ COMMON_ENVIRONMENT }}_{{ COMMON_DEPLOYMENT }}_test_', '']
        -
          # These defaults are needed, otherwise ansible will throw
          # variable undefined errors for when they are not defined
          # in secret vars
          - db_name: "{{ EDXAPP_MYSQL_DB_NAME|default('None') }}"
            db_host: "{{ EDXAPP_MYSQL_HOST|default('None') }}"
            db_user: "{{ edxapp_db_root_user }}"
            db_pass: "{{ edxapp_db_root_pass }}"
          - db_name: "{{ XQUEUE_MYSQL_DB_NAME|default('None') }}"
            db_host: "{{ XQUEUE_MYSQL_HOST|default('None') }}"
            db_user: "{{ xqueue_db_root_user }}"
            db_pass: "{{ xqueue_db_root_pass }}"
          - db_name: "{{ ORA_MYSQL_DB_NAME|default('None') }}"
            db_host: "{{ ORA_MYSQL_HOST|default('None') }}"
            db_user: "{{ ora_db_root_user }}"
            db_pass: "{{ ora_db_root_pass }}"
          - db_name: "{{ DISCERN_MYSQL_DB_NAME|default('None') }}"
            db_host: "{{ DISCERN_MYSQL_HOST|default('None') }}"
            db_user: "{{ discern_db_root_user }}"
            db_pass: "{{ discern_db_root_pass }}"
