- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: False
  roles:
    - common
    - role: nginx
      nginx_sites:
      - devpi
    - role: supervisor
      supervisor_servers:
      - devpi
    - devpi
 
