- name: Create ec2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - role: launch_instance
      keypair: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      ami_image: "{{ ami }}"
      region: "{{ region }}"
      instance_tags: "{{ instance_tags }}"
      size: "{{ size }}"


- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  tasks:
    - debug: msg="test"
