- name: Create sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: continuous-integration
    instance_type: m1.small
    security_group: sandbox
    image: ami-d0f89fb9
    region: us-east-1
    instance_tags: '{"disposable": "true"}'
    size: 50
  roles:
    - launch_instance

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  tasks:
    - debug: msg="test"
