- name: Create ec2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
    - ec2_lookup:
        region: "{{ region }}"
        tags:
          Name: "{{ name_tag }}"
      register: tag_lookup
    - fail: 'Too many results returned, not terminating!'
      when: tag_lookup.instance_ids|length > 1
    - ec2:
        state: 'absent'
        region: "{{ region }}"
        instance_ids: ${tag_lookup.instance_ids}
  roles:
    - role: launch_ec2
      keypair: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      ami_image: "{{ ami }}"
      region: "{{ region }}"
      instance_tags: "{{ instance_tags }}"
      root_ebs_size: "{{ root_ebs_size }}"
      dns_name: "{{ dns_name }}"
      dns_zone: "{{ dns_zone }}"

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  roles:
    # gh_users hash must be passed
    # in as a -e variable
    - gh_users
