- name: Deploy edxapp
  hosts: all
  sudo: True
  gather_facts: True
  vars_files:
    - ["{{ secure_vars }}", "dummy.yml"]
  roles:
    - role: nginx
      nginx_sites:
        - lms
        - cms
    - edxapp
