- hosts: tag_role_elasticsearch:&tag_environment_stage
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/common/common.yml"
    - "{{ secure_dir }}/vars/stage/stage-edx.yml"
  roles:
    - common
    - gh_users
    - oraclejdk
    - elasticsearch
