- name: restarts supervisor
  hosts: all
  sudo: True
  gather_facts: False
  var_files:
    - common/defaults/main.yml
    - supervisor/defaults/main.yml
  tasks:
    - name: supervisor | restart supervisor
      service: >
        name={{ supervisor_service }}
        state=restarted
