- name: Deploy xqueue
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    enable_datadog: True
    enable_newrelic: True
  vars_files:
    - ["{{ secure_vars }}", "dummy.yml"]
  roles:
    - role: nginx
      nginx_sites:
      - xqueue
    - role: xqueue
    - role: datadog
      when: enable_datadog
    - role: newrelic
      when: enable_datadog
