
- include: ease.yml

- name: ora | See if edx-ora.conf is installed
  shell: "[ -f /etc/init/edx-ora.conf ] && echo 'Found' || echo ''"
  register: edx_ora_installed
  tags:
  - deploy

- name: ora | See if edx-ora-celery.conf is installed
  shell: "[ -f /etc/init/edx-ora-celery.conf ] && echo 'Found' || echo ''"
  register: edx_ora_celery_installed
  tags:
  - deploy

# Stop ora service.
- name: ora | stop edx-ora service
  service: name=edx-ora state=stopped
  when: edx_ora_installed.stdout == 'Found'
  notify: ora | restart edx-ora
  tags:
  - deploy

- name: ora | stop edx-ora-celery service
  service: name=edx-ora-celery state=stopped
  when: edx_ora_celery_installed.stdout == 'Found'
  notify: ora | restart edx-ora-celery
  tags:
  - deploy

- name: ora | create ora application config
  template: src=ora.env.json.j2 dest={{ora_app_dir}}/ora.env.json
  sudo_user: "{{ ora_user }}"
  tags:
  - deploy

- name: ora | create ora auth file
  template: src=ora.auth.json.j2 dest={{ora_app_dir}}/ora.auth.json
  sudo_user: "{{ ora_user }}"
  tags:
  - deploy

- name: ora | create ora upstart script
  template: src=edx-ora.conf.j2 dest=/etc/init/edx-ora.conf
  tags:
  - deploy

- name: ora | create ora-celery upstart script
  template: src=edx-ora-celery.conf.j2 dest=/etc/init/edx-ora-celery.conf
  tags:
  - deploy

# Do A Checkout
- name: ora | git checkout ora repo into {{ ora_app_dir }}
  git: dest={{ ora_code_dir }} repo={{ ora_source_repo }} version={{ ora_version }}
  sudo_user: "{{ ora_user }}"
  notify:
    - ora | restart edx-ora
    - ora | restart edx-ora-celery
  tags:
  - deploy

# TODO: Check git.py _run_if_changed() to see if the logic there to skip running certain
# portions of the deploy needs to be incorporated here.


# Install the python pre requirements into {{ ora_venv_dir }}
- name: ora | install python pre-requirements
  pip: requirements="{{ ora_pre_requirements_file }}" virtualenv="{{ ora_venv_dir }}" state=present
  sudo_user: "{{ ora_user }}"
  notify:
    - ora | restart edx-ora
    - ora | restart edx-ora-celery
  tags:
  - deploy

# Install the python post requirements into {{ ora_venv_dir }}
- name: ora | install python post-requirements
  pip: requirements="{{ ora_post_requirements_file }}" virtualenv="{{ ora_venv_dir }}" state=present
  sudo_user: "{{ ora_user }}"
  notify:
    - ora | restart edx-ora
    - ora | restart edx-ora-celery
  tags:
  - deploy

  #Needed if using redis to prevent memory issues
- name: ora | change memory commit settings -- needed for redis
  command: sysctl vm.overcommit_memory=1
  notify:
    - ora | restart edx-ora
    - ora | restart edx-ora-celery
  tags:
  - deploy

- name: ora | syncdb and migrate
  shell: SERVICE_VARIANT=ora {{ora_venv_dir}}/bin/django-admin.py syncdb --migrate --noinput --settings=edx_ora.aws --pythonpath={{ora_code_dir}}
  when: migrate_db is defined and migrate_db|lower == "yes"
  sudo_user: "{{ ora_user }}"
  notify:
    - ora | restart edx-ora
    - ora | restart edx-ora-celery
  tags:
  - deploy

- name: ora | create users
  shell: SERVICE_VARIANT=ora {{ora_venv_dir}}/bin/django-admin.py update_users --settings=edx_ora.aws --pythonpath={{ora_code_dir}}
  sudo_user: "{{ ora_user }}"
  notify:
    - ora | restart edx-ora
    - ora | restart edx-ora-celery
  tags:
  - deploy
