# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---

- name: ora | create application user
  user: >
    name="{{ ora_user }}"
    home="{{ ora_app_dir }}"
    createhome=no
    shell=/bin/false

- name: ora | create ora app and data dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ ora_user }}"
    group="{{ common_web_group }}"
  with_items:
    - "{{ ora_venvs_dir }}"
    - "{{ ora_app_dir }}"
    - "{{ ora_data_dir }}"
    - "{{ ora_app_dir }}/ml_models"

- name: ora | install debian packages that ora needs
  apt: pkg={{item}} state=present
  with_items: ora_debian_pkgs

- name: ora | install debian packages for ease that ora needs
  apt: pkg={{item}} state=present
  with_items: ora_ease_debian_pkgs

- include: deploy.yml

- name: ora | create a symlink for venv python
  file: >
    src="{{ ora_venv_bin }}/python"
    dest={{ cfg_dir }}/python.ora
    state=link
