---
- name: JSCover | Install Java
  apt: pkg=openjdk-7-jre-headless state=present

- name: JSCover | Download JSCover
  get_url: url={{ jscover_url }} dest=/var/tmp/jscover.zip

- name: JSCover | Unzip JSCover
  shell: unzip /var/tmp/jscover.zip -d /var/tmp/jscover
         creates=/var/tmp/jscover

- name: JSCover | Install JSCover JAR
  command: cp /var/tmp/jscover/target/dist/JSCover-all.jar /usr/local/bin/JSCover-all.jar
           creates=/usr/local/bin/JSCover-all.jar

- name: JSCover | Set JSCover permissions
  file: path="/usr/local/bin/JSCover-all.jar" state=file
        owner=root group=root mode=0755
