---

# Ensure that code executed by the worker can't be
# installed to execute on login.
- name: Set permissions on .bash_profile
  file: path="{{ jenkins_user_home }}/.bash_profile" state=file
        owner="{{ jenkins_user }}" group="{{ jenkins_group }}"
        mode=0500

- name: Set permissions on .bashrc
  file: path="{{ jenkins_user_home }}/.bashrc" state=file
        owner="{{ jenkins_user }}" group="{{ jenkins_group }}"
        mode=0500

- name: Set permissions on rbenv config
  file: path="{{ jenkins_user_home }}/ruby_env" state=file
        owner="{{ jenkins_user }}" group="{{ jenkins_group }}"
        mode=0500
  ignore_errors: yes
