# requires:
#  - common/tasks/main.yml
#  - nginx/tasks/main.yml
---
# Check out mitx repo to $app_base_dir
- name: set permissions on $app_base_dir sgid for edx
  file: path=$app_base_dir owner=root group=edx mode=2775 state=directory
  file: path=$app_base_dir owner=ubuntu group=edx mode=2775 state=directory
  sudo: True
- name: install git and its recommends
  apt: pkg=git state=installed install_recommends=yes force=yes
  sudo: True
- name : install python and its recommends
  apt: pkg=python state=installed install_recommends=yes force=yes
  sudo: True
- name : install python pip and its recommends
  apt: pkg=python-pip state=installed install_recommends=yes force=yes
  sudo: True
- name: git checkout configuration repo into $app_base_dir
  git: dest=$app_base_dir/configuration repo=git@github.com:edx/configuration.git version=vik/ml-api
- name: install requirements in python using pip
  pip: requirements=$app_base_dir/configuration/ansible-requirements.txt
- name: uploads any needed secret config files
  file: src=../../../../../edx-secret dest=/path/to/symlink owner=ubuntu group=edx state=file