---
- name: edxapp | start edxapp
  service: name=edxapp state=started
  tags:
  - lms
  - lms-preview
  - cms
  - deploy

- name: edxapp | stop edxapp
  service: name=edxapp state=stopped
  tags:
  - lms
  - lms-preview
  - cms
  - deploy

- name: edxapp | restart edxapp
  service: name=edxapp state=restarted
  tags:
  - lms
  - lms-preview
  - cms
  - deploy
