---
- name: "edxapp | restart edxapp:lms"
  supervisorctl: >
    state=restarted
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    name="edxapp:lms"
  sudo_user: "{{ supervisor_user }}"

- name: "edxapp | restart edxapp:cms"
  supervisorctl: >
    state=restarted
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    name="edxapp:cms"
  sudo_user: "{{ supervisor_user }}"


