---
# Restart Start all services.
- name: restart lms
  service: name=lms state=restarted
  tags:
  - lms
  - deploy

- name: restart lms-xml
  service: name=lms-xml state=restarted
  tags:
  - lms-xml
  - deploy

- name: restart lms-preview
  service: name=lms-preview state=restarted
  tags:
  - lms-preview
  - deploy

- name: restart cms
  service: name=cms state=restarted
  tags:
  - cms
  - deploy
