shib:
  sp_entity_id: 'https://class.stanford.edu/shibboleth'
  idp_entity_id: 'https://idp.stanford.edu/'
  idp_metadata_url: 'https://idp.stanford.edu/Stanford-metadata.xml'
  support_email: 'bugs@class.stanford.edu'
  sp_key: |
    YOU NEED TO GENERATE A REAL KEY HERE USING OPENSSL
  sp_pem: |
    THE CORRESPONDING CERTIFICATE PEM GOES HERE
