---
devpi_app_dir: "{{ COMMON_APP_DIR }}/devpi"
devpi_venvs_dir: "{{ devpi_app_dir }}/venvs"
devpi_venv_dir: "{{ devpi_venvs_dir }}/devpi"
devpi_venv_bin: "{{ devpi_venv_dir }}/bin"
devpi_pip_pkgs:
  - devpi-server
  - eventlet
devpi_nginx_port: 80
devpi_port: 4040
devpi_data_dir: "{{ COMMON_DATA_DIR }}/devpi"
devpi_user: devpi
devpi_group: devpi
devpi_server_name: 'pypy.*'
