---

rbenv_version: 'v0.4.0'
rbenv_bundler_version: '1.3.2'
rbenv_root: "{{ rbenv_dir }}/.rbenv"
rbenv_bin: "{{ rbenv_dir }}/.rbenv/bin"
rbenv_shims: "{{ rbenv_root }}/shims"
rbenv_path: "{{ rbenv_bin }}:{{ rbenv_shims }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
rbenv_debian_pkgs:
  - build-essential
  - git
  - libcurl4-openssl-dev
  - libmysqlclient-dev
  - libreadline-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - zlib1g-dev
rbenv_environment:
  RBENV_ROOT: $rbenv_root
  PATH: $rbenv_path
