# Variables for nginx role
---

nginx_app_dir: "{{ app_dir }}/nginx"
nginx_data_dir: "{{ data_dir }}/nginx"
nginx_conf_dir: "{{ app_dir }}/conf.d"
nginx_log_dir: "{{ log_dir }}/nginx"
nginx_sites_available_dir: "{{ nginx_app_dir }}/sites-available"
nginx_sites_enabled_dir: "{{ nginx_app_dir }}/sites-enabled"
nginx_user: root

pkgs:
  nginx:
    state: installed

nginx_xserver_gunicorn_hosts:
  - 127.0.0.1
nginx_xqueue_gunicorn_hosts:
  - 127.0.0.1
nginx_ora_gunicorn_hosts:
  - 127.0.0.1
nginx_lms_gunicorn_hosts:
  - 127.0.0.1
nginx_lms_preview_gunicorn_hosts:
  - 127.0.0.1
nginx_cms_gunicorn_hosts:
  - 127.0.0.1

nginx_cfg:
  #   - link - turn on
  #   - absent - turn off
  sites_enabled:
    basic_auth: link
    edx_release: link
  # path to version files for the basic
  # nginx configuration
  version_html: $app_dir/versions.html
  version_json: $app_dir/versions.json
  # default htpasswd contents set to edx/edx
  # this value can be overiden in vars/secure/<group>.yml
  htpasswd: |
    edx:$apr1$2gWcIvlc$Nu7b/KTwd5HoIDEkSPNUk/
