#Add rabbitmq to sources.  See http://www.rabbitmq.com/install-debian.html
- name: add in rabbitmq line to sources.list
  lineinfile: dest=/etc/apt/sources.list state=present line="deb http://www.rabbitmq.com/debian/ testing main" regexp='^deb http://www.rabbitmq.com/debian/ testing main'

- name: add rabbit key
  apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: install rabbitmq
  apt: pkg=rabbitmq-server install_recommends=yes state=present update_cache=yes
  notify: restart rabbitmq






