# requires:
#   - common/tasks/main.yml
---
- name: Install nginx
  sudo: True
  apt: pkg=nginx state={{ pkgs.nginx.state }}
  notify: restart nginx
  tags:
  - nginx
# removing default link
- name: Removing default nginx config (enabled)
  sudo: True
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  tags:
  - nginx
- name: Removing default nginx config (available)
  sudo: True
  file: path=/etc/nginx/sites-available/default state=absent
  tags:
  - nginx
# Standard configuration that is common across all roles
# Default values for these variables are set in group_vars/all
# Note: remove spaces in {{..}}, otherwise you will get a template parsing error.
- include: nginx_site.yml state={{nginx_cfg.sites_enabled.edx_release}} site_name=edx-release
- include: nginx_site.yml state={{nginx_cfg.sites_enabled.basic_auth}} site_name=basic-auth
# Default htpassword file, required for basic auth
- copy: content={{ nginx_cfg.htpasswd }} dest=/etc/nginx/nginx.htpasswd
  sudo: True
  tags:
  - nginx
- name: Ensuring that nginx is running
  sudo: True
  service: name=nginx state=started
  tags:
  - nginx
