# Requires nginx package
---
- name: nginx | Copying nginx config {{ site_name }}
  template: src={{ item }} dest=/etc/nginx/sites-available/{{ site_name }} owner=root group=root mode=0600
  notify: nginx | restart nginx
  tags:
  - nginx
  - lms
  - cms
  - nginx-env
  - update
  - deploy

- name: nginx | Creating nginx config link {{ site_name }}
  file: src=/etc/nginx/sites-available/{{ site_name }} dest=/etc/nginx/sites-enabled/{{ site_name }} state={{ state }} owner=root group=root
  notify: nginx | restart nginx
  when: nginx_role_run is defined
  tags:
  - nginx
  - lms
  - cms
  - nginx-env
  - update
  - deploy
