#- hosts: tag_environment_prod:&tag_function_webserver
- hosts: ~tag_Name_app(test)_prod
#- hosts: tag_environment_prod:&tag_function_webserver
#- hosts: security_group_edx-prod-EdxappServerSecurityGroup-NSKCQTMZIPQB
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_prod_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/edxapp_prod_users.yml"
    - "{{ secure_dir }}/vars/shib_prod_vars.yml"

  vars:
    secure_dir: '../../../configuration-secure/ansible'
    # this indicates the path to site-specific (with precedence)
    # things like nginx template files
    local_dir:  '../../../configuration-secure/ansible/local'

  roles:
    - common
    - nginx
    - edxapp
    - apache
    - shibboleth
    # run this role last
    - in_production
