---

- name: jenkins | install jenkins specific system packages
  apt:
    pkg={{','.join(jenkins_debian_pkgs)}}
    state=present update_cache=yes
  tags:
  - jenkins

- name: common | Create jenkins group
  group: name={{ jenkins_group }} state=present

- name: jenkins | Add the jenkins user to the group
  user: name={{ jenkins_user }} append=yes groups={{ jenkins_group }}

- name: jenkins | Install Jenkins apt key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: jenkins | Add apt repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: jenkins | Install jenkins package
  apt: pkg=jenkins state=present update_cache=yes

- name: jenkins | Make plugins directory
  sudo_user: jenkins
  shell: mkdir -p {{ jenkins_home }}/plugins

- name: jenkins | Install Jenkins plugins
  sudo_user: jenkins
  get_url: url=http://updates.jenkins-ci.org/download/plugins/${item.name}/${item.version}/${item.name}.hpi
           dest={{ jenkins_home }}/plugins/${item.name}.hpi
  with_items: "{{ jenkins_plugins }}"
  notify:
    - restart Jenkins

# We had to fork the git-client plugin repo
# to fix an obscure bug.  If and when the PR gets
# merged into the main repo and released,
# we can use the regular plugin install process.
# Until then, we need to compile and install it ourselves.
- name: jenkins | Checkout custom git-client plugin repo
  git: repo=https://github.com/edx/git-client-plugin.git
       dest=/tmp/git-client-plugin

- name: jenkins | Compile custom git-client plugin
  command: mvn install chdir=/tmp/git-client-plugin
           creates=/tmp/git-client-plugin/target/git-client.hpi

- name: jenkins | Install custom git-client
  command: mv /tmp/git-client-plugin/target/git-client.hpi
           {{ jenkins_home }}/plugins/git-client.hpi
           creates={{ jenkins_home }}/plugins/git-client.hpi
  notify:
    - restart Jenkins

- name: jenkins | Set git-client plugin permissions
  file: path={{ jenkins_home }}/plugins/git-client.hpi
        owner={{ jenkins_user }} group={{ jenkins_group }}
        mode=700

- name: jenkins | Setup nginix vhost
  template:
    src=etc/nginx/sites-available/jenkins.j2
    dest=/etc/nginx/sites-available/jenkins

- name: jenkins | enable jenkins vhost
  file:
    src=/etc/nginx/sites-available/jenkins
    dest=/etc/nginx/sites-enabled/jenkins
    state=link
  notify: jenkins | start nginx
