# Installs packages to run edx locally on a single instance
# requires:
#  - group_vars/all
#  - common/tasks/main.yml
#
#  This installs mysql-server-5.5 though
#  in production we use mysql-5.1.62.
#
#  We could install from source instead:
#  http://downloads.mysql.com/archives/mysql-5.1/mysql-5.1.62.tar.gz
#
---
- name: install packages needed for single server
  apt: pkg={{','.join(edxlocal_debian_pkgs)}} install_recommends=yes state=present

- name: create a database for edxapp
  mysql_db: >
    db=edxapp
    login_user={{ EDXAPP_MYSQL_USER  }}
    login_password={{ EDXAPP_MYSQL_PASSWORD }}
    state=present
    encoding=utf8
  when: EDXAPP_MYSQL_USER
    
- name: create a database for xqueue
  mysql_db: >
    db=xqueue
    login_user={{ XQUEUE_MYSQL_USER  }}    
    login_password={{ XQUEUE_MYSQL_PASSWORD }}    
    state=present
    encoding=utf8
  when: XQUEUE_MYSQL_USER    

- name: create a database for ora
  mysql_db: >
    db=ora
    login_user={{ ORA_MYSQL_USER  }}    
    login_password={{ ORA_MYSQL_PASSWORD }}    
    state=present
    encoding=utf8
  when: ORA_MYSQL_USER    

- name: create a database for discern
  mysql_db: >
    db=discern
    login_user={{ DISCERN_MYSQL_USER  }}    
    login_password={{ DISCERN_MYSQL_PASSWORD }}    
    state=present
    encoding=utf8
  when: DISCERN_MYSQL_USER    


- name: install memcached
  apt: pkg=memcached state=present
