# Installs packages to run edx locally on a single instance
# requires:
#  - group_vars/all
#  - common/tasks/main.yml
#  - nginx/tasks/main.yml
#
#  This installs mysql-server-5.5 though
#  in production we use mysql-5.1.62.
#
#  We could install from source instead:
#  http://downloads.mysql.com/archives/mysql-5.1/mysql-5.1.62.tar.gz
#
---
- name: edxlocal | install python-pymongo (req for ansible)
  pip: name=pymongo

- name: edxlocal | install python-mysqldb (req for ansible)
  apt: pkg=python-mysqldb state=present

- name: edxlocal | install mysql server and recommends
  apt: pkg=mysql-server-5.5 state=present install_recommends=yes

- name: edxlocal | create a database for edxapp
  mysql_db: >
    db=edxapp
    state=present
    encoding=utf8

- name: edxlocal | create a database for xqueue
  mysql_db: >
    db=xqueue
    state=present
    encoding=utf8

- name: edxlocal | create a database for ora
  mysql_db: >
    db=ora
    state=present
    encoding=utf8

- name: edxlocal | install mongo server and recommends
  apt: pkg=mongodb-server state=present install_recommends=yes

- name: edxlocal | stop mongo service
  service: name=mongodb state=stopped

- name: edxlocal | move mongodb to /mnt
  command: mv /var/lib/mongodb  /mnt/.  creates=/mnt/mongodb

- name: edxlocal | create mongodb symlink
  file: src=/mnt/mongodb dest=/var/lib/mongodb state=link

- name: edxlocal | start mongo service
  service: name=mongodb state=started

- name: edxlocal | wait for mongo server to start
  wait_for: port=27017 delay=2

- name: edxlocal | create a mongodb user for edxapp
  mongodb_user: >
    database=edxapp
    name=edxapp
    password=password
    state=present

- name: edxlocal | create a mongodb user for forums
  mongodb_user: >
    database=cs_comments_service
    name=cs_comments_service
    password=password
    state=present

- name: edxlocal | install edxlocal specific system packages
  apt: pkg={{','.join(edxlocal_debian_pkgs)}} state=present

- name: Git clone ruby-build
  shell: git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build creates=~/.rbenv/plugins/ruby-build

- name: install ruby-build
  shell: sh install.sh chdir=~/.rbenv/plugins/ruby-build/

- name: Install ruby version
  shell: yes n|rbenv install 1.9.3-p374
  ignore_errors: yes

- name: Set rbenv version
  shell: rbenv global 1.9.3-p374

- name: Install gcli
  shell: rbenv exec gem install github_cli

# This is done so that it will not report back to github while testing
- name: TEMPORARILY DISABLE gcli
  shell: echo "#!/bin/bash\necho gcli" > /usr/local/bin/gcli
