common_debian_pkgs:
  - ack-grep
  - lynx-cur
  - logrotate
  - mosh
  - rsyslog
  - screen
  - tree
  - git
  - unzip
  - python2.7
  - python-pip
  - python2.7-dev

common_pip_pkgs:
  - virtualenv
  - virtualenvwrapper

common_web_user: www-data
common_web_group: www-data
common_log_user: syslog
