
# Override these variables
# to change the base directory
# where edX is installed
COMMON_DATA_DIR: /edx/var
COMMON_APP_DIR: /edx/app
COMMON_LOG_DIR: "{{ COMMON_DATA_DIR }}/log"

# these directories contain
# symlinks for convenience
COMMON_BIN_DIR: /edx/bin
COMMON_CFG_DIR: /edx/etc

COMMON_ENV_NAME: 'default_env'
COMMON_ENV_TYPE: 'default_type'
COMMON_PYPI_MIRROR_URL: 'https://pypi.python.org/simple'
# do not include http/https
COMMON_GIT_MIRROR: 'github.com'



common_debian_pkgs:
  - ack-grep
  - lynx-cur
  - logrotate
  - mosh
  - rsyslog
  - screen
  - tree
  - git
  - unzip
  - python2.7
  - python-pip
  - python2.7-dev

common_pip_pkgs:
  - virtualenv
  - virtualenvwrapper

common_web_user: www-data
common_web_group: www-data
common_log_user: syslog
