---
- name: discern | restart discern
  supervisorctl: >
    name=discern
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=restarted

- name: discern | restart discern_celery
  supervisorctl: >
    name=discern_celery
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=restarted
