# administrator accounts, added to all roles
# The create_users role task automatically adds all these users to the 
# 'adm' and 'edx' system groups
admin_users:
- user: joe
  email: joe@example.com
  groups:
  - adm

admin_keys:
- user: joe
  path: keys/joe.key
