---
gh_mirror_nginx_port: 80
gh_mirror_server_name: 'git.*'
gh_mirror_data_dir: /var/git/mirrors
gh_mirror_app_dir: /opt/gh_mirror
gh_mirror_user: git-mirror
gh_mirror_group: git-mirror
gh_mirror_orgs:
  - edX
  - MITx
  - eventbrite
  - dementrock
  - mfogel
gh_mirror_pip_pkgs:
  - pyyaml
  - requests
gh_mirror_app_files:
  - repos_from_orgs.py
