---
gh_mirror_nginx_port: 80
gh_mirror_server_name: 'git.*'
gh_mirror_data_dir: /var/git/mirrors
gh_mirror_app_dir: /opt/gh_mirror
gh_mirror_user: git-mirror
gh_mirror_group: git-mirror
gh_mirror_orgs:
  - edX
  - MITx
  - eventbrite
  - dementrock
  - mfogel
gh_mirror_debian_pkgs:
  - python-yaml
  - python-requests
gh_app_files:
  - gh_mirror_cron.sh
  - repo_from_orgs.py
