---

- name: forum | create the supervisor wrapper
  template: >
    src={{ forum_supervisor_wrapper|basename }}.j2
    dest={{ forum_supervisor_wrapper }}
    mode=0755
  sudo_user: "{{ forum_user }}"
  notify: forum | restart the forum service
  tags:
  - deploy

- name:  forum | git checkout forum repo into {{ forum_code_dir }}
  git: dest={{ forum_code_dir }} repo={{ forum_source_repo }} version={{ forum_version }}
  sudo_user: "{{ forum_user }}"
  notify: forum | restart the forum service
  tags:
  - deploy

# TODO: This is done as the common_web_user
# since the process owner needs write access
# to the rbenv
- name: forum | install comments service bundle
  shell: bundle install chdir={{ forum_code_dir }}
  sudo_user: "{{ common_web_user }}"
  environment: "{{ forum_environment }}"
  notify: forum | restart the forum service
  tags:
  - deploy

- name: forum | create the supervisor config
  template: >
    src=forum.conf.j2 dest={{ supervisor_cfg_dir }}/forum.conf
    owner={{ common_web_user }} group={{ supervisor_user }}
    mode=0644
  register: forum_supervisor
  notify: forum | restart the forum service
  tags:
  - deploy
