- name: stop forum service
  service: name=cs_comments_service state=stopped
  tags:
  - forum
  - deploy

- name: git checkout forum repo into $app_base_dir
  git: dest={{forum_code_dir}} repo={{forum_source_repo}} version={{forum_version}}
  sudo: yes
  sudo_user: ${forum_user}
  tags:
  - forum
  - deploy

- name: install comments service bundle
  shell: executable=/bin/bash {{ rbenv_root }}/bin/bundle install chdir={{ forum_code_dir }}
  sudo: yes
  sudo_user: ${forum_user}
  tags:
    - forum
    - install

- name: start forum service
  service: name=cs_comments_service state=started
  tags:
  - forum
  - deploy