---

# forum
#
# Dependencies:
#
#   * common
#   * elasticsearch
#   * oraclejdk
#   * rbenv
#
#
# Example play:
#   roles:
#   - common
#   - oraclejdk
#   - elasticsearch
#   - role: rbenv
#     rbenv_user: "{{ forum_user }}"
#     rbenv_dir: "{{ forum_rbenv_dir }}"
#     rbenv_ruby_version: "{{ forum_ruby_version }}"
#   - forum

- name: forum | create application user
  user: >
    name="{{ forum_user }}"
    home="{{ forum_app_dir }}"
    createhome=no
    shell=/bin/false

- name: forum | create forum app dir
  file: >
    path="{{ forum_app_dir }}"
    state=directory
    owner="{{ forum_user }}"
    group="{{ common_web_group }}"

- name: forum | setup the forum env
  template: src=forum_env.j2 dest={{ forum_app_dir }}/forum_env
  sudo_user: "{{ forum_user }}"
  notify:
    - forum | restart the forum service

- name: forum | copy cs_comments_service SysVunit script
  template: src=cs_comments_service.j2 dest=/etc/init.d/cs_comments_service owner=root group=root mode=750
  notify:
    - forum | restart the forum service
  tags:
  - forum
  - install
  when: ansible_distribution == 'Debian'

- name: forum | copy cs_comments_service upstart script
  template: src=cs_comments_service.conf.j2 dest=/etc/init/cs_comments_service.conf owner=root group=root mode=644
  notify:
    - forum | restart the forum service
  tags:
  - forum
  - install
  when: ansible_distribution == 'Ubuntu'

- include: deploy.yml
- include: test.yml
