---

# forum
#
# Dependencies:
#
#   * common
#   * elasticsearch
#   * oraclejdk
#   * rbenv
#
#
# Example play:
#   roles:
#   - common
#   - oraclejdk
#   - elasticsearch
#   - role: rbenv
#     rbenv_user: "{{ forum_user }}"
#     rbenv_dir: "{{ forum_rbenv_dir }}"
#     rbenv_ruby_version: "{{ forum_ruby_version }}"
#   - forum

- name: forum | create application user
  user: >
    name="{{ forum_user }}" home="{{ forum_app_dir }}"
    createhome=no
    shell=/bin/false
  notify: forum | restart the forum service

- name: forum | create forum app dir
  file: >
    path="{{ forum_app_dir }}" state=directory
    owner="{{ forum_user }}" group="{{ common_web_group }}"
  notify: forum | restart the forum service

- name: forum | setup the forum env
  template: >
    src=forum_env.j2 dest={{ forum_app_dir }}/forum_env
    owner={{ forum_user }}  group={{ common_web_user }}
    mode=0644
  notify:
    - forum | restart the forum service

- name: forum | create the supervisor config
  template: >
    src=forum.conf.j2 dest={{ supervisor_cfg_dir }}/forum.conf
    owner={{ common_web_user }} group={{ supervisor_user }}
    mode=0644
  register: forum_supervisor

- include: deploy.yml

  # call supervisorctl update. this reloads
  # the supervisorctl config and restarts
  # the services if any of the configurations
  # have changed.
  #
  # we don't use notifications for supervisor because
  # they don't work well with parameterized roles.
  # See https://github.com/ansible/ansible/issues/4853
- name: forum | update supervisor configuration
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  register: supervisor_update
  changed_when: supervisor_update.stdout != ""

- include: test.yml

