---

# forum
#
# Dependencies:
#
#   * common
#   * elasticsearch
#   * oraclejdk
#   * rbenv
#
#
# Example play:
#   roles:
#   - common
#   - oraclejdk
#   - elasticsearch
#   - role: rbenv
#     rbenv_user: "{{ forum_user }}"
#     rbenv_dir: "{{ forum_rbenv_dir }}"
#     rbenv_ruby_version: "{{ forum_ruby_version }}"
#   - forum

- name: forum | create application user
  user: >
    name="{{ forum_user }}"
    home="{{ forum_app_dir }}"
    createhome=no
    shell=/bin/false

- name: forum | create forum app dir
  file: >
    path="{{ forum_app_dir }}"
    state=directory
    owner="{{ forum_user }}"
    group="{{ common_web_group }}"

- name: forum | setup the forum env
  template: src=forum_env.j2 dest={{ forum_app_dir }}/forum_env
  sudo_user: "{{ forum_user }}"
  notify:
    - forum | restart the forum service

- include: deploy.yml

- name: forum | create the supervisor config
  template: src=forum.conf.j2 dest={{ supervisor_cfg_dir }}/forum.conf
  notify:
    - forum | restart the forum service
- include: test.yml
