DISCERN_NGINX_PORT: 18070
DISCERN_BASIC_AUTH: False

discern_app_dir: "{{ app_dir }}/discern"
discern_code_dir: "{{ discern_app_dir }}/discern"
discern_data_dir: "{{ data_dir }}/discern"
discern_venv_dir: "{{ venvs_dir }}/discern"
discern_venv_bin: "{{ discern_venv_dir }}/bin"
discern_pre_requirements_file: "{{ discern_code_dir }}/pre-requirements.txt"
discern_post_requirements_file: "{{ discern_code_dir }}/requirements.txt"
discern_user: "discern"

discern_ease_venv_dir: "{{ discern_venv_dir }}"
discern_ease_code_dir: "{{ app_dir }}/ease"
discern_ease_source_repo: https://github.com/edx/ease.git
discern_ease_version: 'HEAD'
discern_ease_pre_requirements_file: "{{ discern_ease_code_dir }}/pre-requirements.txt"
discern_ease_post_requirements_file: "{{ discern_ease_code_dir }}/requirements.txt"

discern_nltk_data_dir: "{{ discern_data_dir}}/nltk_data"

discern_source_repo: https://github.com/edx/discern.git
discern_settings: discern.aws
discern_branch: dev
discern_gunicorn_port: 8070
discern_gunicorn_host: 127.0.0.1

discern_debian_pkgs:
  - policykit-1
  - python-virtualenv
  - gcc
  - g++
  - build-essential
  - python-dev
  - gfortran
  - libfreetype6-dev
  - libpng12-dev
  - libxml2-dev
  - libxslt-dev
  - libreadline6
  - libreadline6-dev
  - redis-server
  - python-pip
  - ipython
  - nginx
  - libmysqlclient-dev
  - libblas3gf
  - libblas-dev
  - liblapack3gf
  - liblapack-dev
  - libatlas-base-dev
  - curl
  - yui-compressor

discern_ease_debian_pkgs:
  - python-pip
  - gcc
  - g++
  - gfortran
  - libblas3gf
  - libblas-dev
  - liblapack3gf
  - liblapack-dev
  - libatlas-base-dev
  - libxml2-dev
  - libxslt1-dev
  - aspell
  - python
