# requires:
#  - common/tasks/main.yml
#  - nginx/tasks/main.yml
---
- name: create lms application config
  template: src=env.json.j2 dest=$app_base_dir/lms.env.json
  sudo: True

- name: create lms auth file
  template: src=auth.json.j2 dest=$app_base_dir/lms.auth.json
  sudo: True

- include: ../../nginx/tasks/nginx_site.yml state=link site_name=lms
- include: ../../nginx/tasks/nginx_site.yml state=link site_name=lms-backend

# Install ssh keys for ubuntu account to be able to check out from mitx
# Temprory behavior, not needed after June 1. Perhaps still useful as a recipe.
# {{ secure_dir }} is relative to the top-level playbooks dir so there is some
# ugly relative pathing here

- name: install read-only ssh key for mitx repo (private)
  copy: src=../../../{{ secure_dir }}/files/git-identity dest=/etc/git-identity force=yes owner=root group=root mode=644
  sudo: True

- name: upload ssh script
  copy: src=git_ssh.sh dest=/tmp/git_ssh.sh force=yes owner=root group=root mode=755
  sudo: True

# Check out mitx repo to $app_base_dir
- name: set permissions on $app_base_dir sgid for edx
  file: path=$app_base_dir owner=root group=edx mode=2775 state=directory
  file: path=$app_base_dir owner=ubuntu group=edx mode=2775 state=directory
  sudo: True
- name: install git and its recommends
  apt: pkg=git state=installed install_recommends=yes 
  sudo: True
- name: git checkout mitx repo into $app_base_dir
  git: dest=$app_base_dir/mitx repo=git@github.com:MITx/mitx.git
  environment:
    GIT_SSH: /tmp/git_ssh.sh
