---
- name: create lms application config
  action: template src=env.json.j2 dest=/opt/wwc/lms-env.json
  sudo: True
- name: create lms auth file
  action: template src=auth.json.j2 dest=/opt/wwc/lms-auth.json
  sudo: True
