---
jenkins_home: /var/lib/jenkins
phantomjs_url: https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
phantomjs_archive: phantomjs-1.9.1-linux-x86_64.tar.bz2
phantomjs_folder: phantomjs-1.9.1-linux-x86_64
