---
jenkins_home: /var/lib/jenkins
phantomjs_url: https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
phantomjs_archive: phantomjs-1.9.1-linux-x86_64.tar.bz2
phantomjs_folder: phantomjs-1.9.1-linux-x86_64
edxlocal_debian_pkgs: ["memcached", "ruby-bundler","rubygems","rbenv","npm","libgraphviz-dev","gfortran","libopenblas-dev","liblapack-dev","libxml2-dev","libgeos-dev","python-dev","libmysqlclient-dev","build-essential","pkg-config","libxslt1-dev","rake"]
ruby_version: 1.9.3-p374
jenkins_plugins:
    - ant.hpi
    - backup.hpi
    - build-name-setter.hpi
    - build-timeout.hpi
    - cobertura.hpi
    - credentials.hpi
    - cvs.hpi
    - dashboard-view.hpi
    - external-monitor-job.hpi
    - ghprb.hpi
    - git.hpi
    - github.hpi
    - git-client.hpi
    - github-api.hpi
    - github-oauth.hpi
    - git-notes.hpi
    - htmlpublisher.hpi
    - javadoc.hpi
    - jobConfigHistory.hpi
    - ldap.hpi
    - mailer.hpi
    - mercurial.hpi
    - nested-view.hpi
    - next-build-number.hpi
    - notification.hpi
    - pam-auth.hpi
    - parameterized-trigger.hpi
    - postbuild-task.hpi
    - rbenv.hpi
    - ruby-runtime.hpi
    - shiningpanda.hpi
    - ssh-credentials.hpi
    - ssh-slaves.hpi
    - subversion.hpi
    - thinBackup.hpi
    - tmpcleaner.hpi
    - token-macro.hpi
    - translation.hpi
    - violations.hpi