
---

- name: mongo | install python pymongo for mongo_user ansible module
  pip: >
    name=pymongo
    state=present
    version=2.6.3
    extra_args="-i {{ PYPI_MIRROR_URL }}"

- name: mongo | add the mongodb signing key
  apt_key: >
    id=7F0CEB10
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present

- name: mongo | add the mongodb repo to the sources list
  apt_repository: >
    repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    state=present

- name: mongo | install mongo server and recommends
  apt: >
    pkg=mongodb-10gen={{ mongo_version }}
    state=present
    install_recommends=yes
    update_cache=yes

- name: mongo | create mongo data dir
  file: >
    path="{{ mongo_data_dir }}"
    state=directory
    owner="{{ mongo_user  }}"

- name: mongo | stop mongo service
  service: name=mongodb state=stopped

- name: mongo | move mongodb to {{ mongo_data_dir }}
  command: mv /var/lib/mongodb  {{ mongo_data_dir}}/.  creates={{ mongo_data_dir }}/mongodb

- name: mongo | copy configuration template
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf backup=yes
  notify: restart mongo

- name: mongo | start mongo service
  service: name=mongodb state=started

- name: mongo | wait for mongo server to start
  wait_for: port=27017 delay=2

- name: mongo | create a mongodb user
  mongodb_user: >
    database={{ item.database }}
    name={{ item.user }}
    password={{ item.password }}
    state=present
  with_items: MONGO_USERS
