
---
- name: edxlocal | install python pymongo for mongo_user ansible module
  pip: >
    name=pymongo
    state=present
    version=2.6.3
    extra_args="-i {{ PYPI_MIRROR_URL }}"
  tags: mongo

- name: edxlocal | add the mongodb signing key
  apt_key: >
    id=7F0CEB10
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present

- name: edxlocal | add the mongodb repo to the sources list
  apt_repository: >
    repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    state=present

- name: edxlocal | install mongo server and recommends
  apt: >
    pkg=mongodb-10gen
    state=present
    install_recommends=yes
    update_cache=yes

- name: mongo | stop mongo service
  service: name=mongodb state=stopped
  tags: mongo

- name: mongo | move mongodb to {{ storage_base_dir }}
  command: mv /var/lib/mongodb  {{ storage_base_dir}}/.  creates={{ storage_base_dir }}/mongodb
  tags: mongo

- name: mongo | create mongodb symlink
  file: src={{ storage_base_dir }}/mongodb dest=/var/lib/mongodb state=link
  tags: mongo

- name: mongo | copy configuration template
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf backup=yes
  notify: restart mongo
  tags: mongo

- name: mongo | start mongo service
  service: name=mongodb state=started
  tags: mongo

- name: mongo | wait for mongo server to start
  wait_for: port=27017 delay=2
  tags: mongo

- name: mongo | create a mongodb user
  mongodb_user: >
    database={{ database }}
    name={{ user }}
    password={{ password }}
    state=present
  with_items: {{MONGO_USERS}}
  tags: mongo
