# Variables used to deploy the CMS and LMS

LMS_VARIANT: lms
CMS_VARIANT: cms
#PATH: /opt/www/.rbenv/shims:/opt/www/.rbenv/bin:/opt/wwc/edx-platfgorm/bin:$$PATH

deploy_environment:
  NO_PREREQ_INSTALL: 1
  SKIP_WS_MIGRATIONS: 1
  RBENV_ROOT: /opt/www/.rbenv
  GEM_HOME: /opt/www/.gem
  PATH: /opt/edx/bin:/opt/wwc/edx-platform/bin:/opt/www/.rbenv/bin:/opt/www/.rbenv/shims:/opt/www/.gem/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
