# Variables used to deploy the CMS and LMS

lms_variant: lms
cms_variant: cms
rbenv_dir: /opt/www/.rbenv
gem_home: /opt/www/.gem

deploy_environment:
  NO_PREREQ_INSTALL: 1
  SKIP_WS_MIGRATIONS: 1
  RBENV_ROOT: "{{ rbenv_dir }}"
  GEM_HOME: "{{ gem_home }}"
  PATH: "{{ venv_dir }}/bin:{{ platform_code_dir }}/bin:{{ rbenv_dir }}/bin:{{ rbenv_dir }}/shims:{{ gem_home }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
