---
dependencies:
  - supervisor
  - role: rbenv
    rbenv_user: "{{ edxapp_user }}"
    rbenv_dir: "{{ edxapp_app_dir }}"
    rbenv_ruby_version: "{{ edxapp_ruby_version }}"
  - devpi
  - role: automated
    automated_rbash_links: "{{ edxapp_automated_rbash_links }}"
    automated_sudoers_dest: '99-automator-edxapp'
    automated_sudoers_template: 'roles/edxapp/templates/etc/sudoers.d/99-automator-edxapp.j2'
