mlapi_source_repo: git@github.com:edx/ml-service-api.git
ml_source_repo: git@github.com:edx/machine-learning.git
ml_dir: $app_base_dir/machine-learning
ml_api_dir: $app_base_dir/ml-service-api
ml_api_settings: ml_service_api.settings
mlapi_debian_pkgs:
  - python
  - gcc
  - g++
  - aspell
  - python-virtualenv
  - build-essential
  - python-dev
  - gfortran
  - libfreetype6-dev
  - libpng12-dev
  - libxml2-dev
  - libxslt1-dev
  - libreadline6
  - libreadline6-dev
  - redis-server
  - python-pip
  - ipython
  - nginx
  - libmysqlclient-dev
  - libblas3gf
  - libblas-dev
  - liblapack3gf
  - liblapack-dev
  - libatlas-base-dev
  - curl
  - yui-compressor