---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role datajam
#
#

- name: datajam | checkout source
  git: dest={{ COMMON_APP_DIR }}/datajam repo="https://github.com/edx/datajam.git" version=master
  sudo_user: "{{ edxapp_user }}"
  tags:
    - deploy

- name: datajam | edxapp scripts
  copy: src={{item}} dest=/usr/local/bin/ mode=0777
  sudo: yes
  with_items:
    - edx-cms-devserver
    - edx-insights-devserver
    - edx-lms-devserver
    - edx-forum-devserver
    - edx-workbench-devserver
  tags:
    - deploy


- name: datajam | install matplotlib dependencies
  apt: pkg={{item}}
  with_items:
    - libpng12-dev
    - libfreetype6-dev
  tags:
    - deploy


- name: datajam | install workbench XBlock dependency
  shell: >
     . {{ edxapp_venv_dir }}/bin/activate && cd {{ edxapp_venv_dir }}/src/xblock/thumbs && python setup.py install && deactivate
  sudo_user: "{{ edxapp_user }}"
  tags:
    - deploy

