---
- name: create mlapi application config
  template: src=env.json.j2 dest=$app_base_dir/env.json
  sudo: True

- name: create mlapi auth file
  template: src=auth.json.j2 dest=$app_base_dir/auth.json
  sudo: True

# Check out mitx repo to $app_base_dir
- name: set permissions on $app_base_dir sgid for edx
  file: path=$app_base_dir owner=root group=edx mode=2775 state=directory
  file: path=$app_base_dir owner=ubuntu group=edx mode=2775 state=directory
  sudo: True
- name: install git and its recommends
  apt: pkg=git state=installed install_recommends=yes
  sudo: True
- name: git checkout ml-service-api repo into $app_base_dir
  git: dest=$app_base_dir/ml-service-api repo=git@github.com:edx/ml-service-api.git
- name: git checkout ml-service-api repo into $app_base_dir
  git: dest=$app_base_dir/machine-learning repo=git@github.com:edx/machine-learning.git
