---
- name: create mlapi application config
  template: src=env.json.j2 dest=$app_base_dir/env.json
  sudo: True

- name: create mlapi auth file
  template: src=auth.json.j2 dest=$app_base_dir/auth.json
  sudo: True

# Check out mitx repo to $app_base_dir
- name: Create virtualenv dir
  sudo: True
  file: path=/opt/edx state=directory owner=ubuntu group=ubuntu
- name: set permissions on $app_base_dir sgid for edx
  file: path=$app_base_dir owner=root group=edx mode=2775 state=directory
  file: path=$app_base_dir owner=ubuntu group=edx mode=2775 state=directory
  file: path=/opt/edx owner=ubuntu group=edx mode=2775 state=directory
  sudo: True
- name: install a bunch of system packages on which mlapi relies
  apt: pkg={{item}} state=present
  with_items: mlapi_debian_pkgs
  sudo: True
- name: git checkout ml-service-api repo into $app_base_dir
  git: dest=$app_base_dir/ml-service-api repo=git@github.com:edx/ml-service-api.git
- name: git checkout ml-service-api repo into $app_base_dir
  git: dest=$app_base_dir/machine-learning repo=git@github.com:edx/machine-learning.git
