---
- name: stop celery
  service: name=celery state=stopped
  sudo: True

- name: stop nginx
  service: name=nginx state=stopped
  sudo: True

- name: stop discern
  service: name=discern state=stopped
  sudo: True

- name: create mlapi application config env.json file
  template: src=env.json.j2 dest=$app_base_dir/env.json
  sudo: True

- name: create mlapi auth file auth.json
  template: src=auth.json.j2 dest=$app_base_dir/auth.json
  sudo: True

- name: change memory commit settings -- needed for redis
  command: sysctl vm.overcommit_memory=1
  sudo: yes

- name: add github to the known hosts file
  shell: ssh-keyscan -H github.com > ~/.ssh/known_hosts

- name: set permissions on $app_base_dir sgid for edx
  file: path=$app_base_dir owner={{remote_user}} group=edx mode=2775 state=directory
  file: path={{venv_dir}} owner={{remote_user}} group=edx mode=2775 state=directory
  sudo: True

- name: Install git so that we can clone repos
  apt: pkg=git install_recommends=yes state=present
  sudo: True

- name: create ml api directory and set permissions
  file: path={{ml_api_dir}} owner={{remote_user}} group=edx mode=2775 state=directory
  sudo: True

- name: create machine learning directory and set permissions
  file: path={{ml_dir}} owner={{remote_user}} group=edx mode=2775 state=directory
  sudo: True

- name: git checkout discern repo into ml_api_dir
  git: dest={{ml_api_dir}} repo={{mlapi_source_repo}} version={{ml_api_branch}}

- name: git checkout machine-learning repo into ml_dir
  git: dest={{ml_dir}} repo={{ml_source_repo}} version={{ml_branch}}

- name: install discern apt packages
  command: xargs -a $app_base_dir/discern/apt-packages.txt apt-get install -y
  sudo: yes

- name: install machine-learning apt packages
  command: xargs -a $app_base_dir/machine-learning/apt-packages.txt apt-get install -y
  sudo: yes

- name : install python pre-requirements for discern
  pip: requirements="{{ml_api_dir}}/pre-requirements.txt" virtualenv="{{venv_dir}}" state=present

- name : install python pre-requirements for machine-learning
  pip: requirements="{{ml_dir}}/pre-requirements.txt" virtualenv="{{venv_dir}}" state=present

- name : install python requirements for discern
  pip: requirements="{{ml_api_dir}}/requirements.txt" virtualenv="{{venv_dir}}" state=present

- name : install python requirements for machine-learning
  pip: requirements="{{ml_dir}}/requirements.txt" virtualenv="{{venv_dir}}" state=present

- name: install machine-learning python package
  shell: command="{{venv_dir}}/bin/activate; cd {{ml_dir}}; python setup.py install"

- name: install nltk data using rendered shell script
  shell: command="{{venv_dir}}/bin/python -m nltk.downloader -d {{nltk_data_dir}} all"

- name: set permissions on nltk data directory
  file: path={{nltk_data_dir}} owner={{remote_user}} group=edx mode=2775 state=directory
  sudo: True

- name: django syncdb for discern
  shell: ls; {{venv_dir}}/bin/python {{ml_api_dir}}/manage.py syncdb --noinput --settings={{ml_api_settings}} --pythonpath={{ml_api_dir}}

- name: django migrate for discern
  shell: ls; {{venv_dir}}/bin/python {{ml_api_dir}}/manage.py migrate --noinput --settings={{ml_api_settings}} --pythonpath={{ml_api_dir}}

- name: django collectstatic for discern
  shell: ls; {{venv_dir}}/bin/python {{ml_api_dir}}/manage.py collectstatic --noinput --settings={{ml_api_settings}} --pythonpath={{ml_api_dir}}

- name: django update_index for discern
  shell: ls; {{venv_dir}}/bin/python {{ml_api_dir}}/manage.py update_index --settings={{ml_api_settings}} --pythonpath={{ml_api_dir}}

- name: render celery service from template
  template: src=celery.conf.j2 dest=/etc/init/celery.conf
  sudo: True

- name: render discern service from template
  template: src=discern.conf.j2 dest=/etc/init/discern.conf
  sudo: True

- name: create nginx directory and set perms
  file: path=/etc/nginx/sites-available owner=root group=edx mode=2775 state=directory
  sudo: True

- name: render nginx sites available
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  sudo: True

- name: start celery
  service: name=celery state=started
  sudo: True

- name: start nginx
  service: name=nginx state=started
  sudo: True

- name: start discern
  service: name=discern state=started
  sudo: True
