---

#
# notifier
# 
# Overview:
# 
# Provides the edX notifier service, a service for sending 
# notifications over messaging protocols.
#
# Dependencies:
#
#   * common
# 
# Example play:
#   roles:
#   - common
#   - notifier
#
- name: notifier | install notifier specific system packages
  apt: pkg={{','.join(notifier_debian_pkgs)}} state=present
  tags:
  - notifier
  - install
  - update

- name: notifier | create notifier user {{ notifier_user }}
  user: 
    name={{ notifier_user }} state=present shell=/bin/bash 
    home={{ notifier_home }} createhome=yes
  tags:
  - notifier
  - install
  - update

- name: notifier | setup the notifier env
  template: 
    src=notifier_env.j2 dest="{{ notifier_home }}/notifier_env" 
    owner="{{ notifier_user }}" group="{{ notifier_user }}"
  tags:
  - notifier
  - install
  - update

- name: notifier | ensure .bashrc exists
  shell: touch {{ notifier_home }}/.bashrc
  sudo: true  
  sudo_user: "{{ notifier_user }}"
  tags:
  - notifier
  - install
  - update

- name: notifier | add source of notifier_env to .bashrc
  lineinfile:
    dest={{ notifier_home }}/.bashrc
    regexp='. {{ notifier_home }}/notifier_env'    
    line='. {{ notifier_home }}/notifier_env'
  tags:
  - notifier
  - install
  - update

- name: notifier | add source venv to .bashrc
  lineinfile:
    dest={{ notifier_home }}/.bashrc
    regexp='. {{ notifier_venv_dir }}/bin/activate'    
    line='. {{ notifier_venv_dir }}/bin/activate'
  tags:
  - notifier
  - install
  - update

- include: deploy.yml