---

##
## for future compliance, when the API comes on line.
##

- name: notifier | restart notifier-scheduler
  supervisorctl: >
    name=notifier-scheduler
    state=restarted
    config={{ supervisor_cfg }}
    supervisorctl_path={{ supervisor_ctl }}

- name: notifier | restart notifier-celery-workers
  supervisorctl: >
    name=notifier-celery-workers
    state=restarted
    config={{ supervisor_cfg }}
    supervisorctl_path={{ supervisor_ctl }}
