- name: Create sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: continuous-integration
    instance_type: m1.small
    security_group: sandbox
    image: ami-d0f89fb9
    region: us-east-1
    instance_tags: '{"auto-provision": "true"}'
  roles:
    - launch_instance

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
    ansible_ssh_private_key_file: /var/lib/jenkins/continuous-integration.pem
    github_user: jarv
    dns_name: test.sandbox.edx.org
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"
  tasks:
    - name: create github user
      user: name={{ github_user }} append=yes groups="adm" shell=/bin/bash
    - name: create ssh dir for user
      file: path=/home/{{github_user}}/.ssh state=directory mode=0600 owner={{github_user}} group={{github_user}}
    - name: copy key for github user
      get_url: url=https://github.com/jarv.keys dest=/home/{{github_user}}/.ssh/authorized_keys mode=0600 owner={{github_user}} group={{github_user}}
    - name: create DNS entry
      local_action: 
        module: route53
        state: present
        type: CNAME 
        value: "{{item.public_ip}}"
        name: "{{dns_name}}"
      with_items: ${ec2.instances} 
