# This playbook is to configuration
# the official edX sandbox instance
# sandbox.edx.org

- name: Configure instance(s)
  hosts: local
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
    mysql5_workaround: True
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
