- name: Configure instance(s)
  hosts: sandbox
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
    mysql5_workaround: True
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
