# This playbook is to configuration
# the official edX sandbox instance
# sandbox.edx.org

- name: Configure instance(s)
  hosts: localhost
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
    mysql5_workaround: True
  vars_files:
    - "secure_example/vars/sandbox_custom.yml"
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
