- name: Configure instance(s)
  hosts: jenkins_test
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
    mysql5_workaround: True
    ansible_ssh_private_key_file: /var/lib/jenkins/continuous-integration.pem
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"
    # overrides specific to the jenkins test playbook
    - "{{ secure_dir }}/vars/edx_jenkins_tests.yml"
  roles:
    - common
    - { role: python-wheel, 
        wheel_archive_url: "https://s3.amazonaws.com/python-wheel/edx-platform.tar", 
        wheel_archive: "edx-platform", 
        wheel_virtualenv: "{{venv_dir}}",
        wheel_requirements: "{{edx_platform_code_dir}}/requirements/edx/wheel.txt" }
    - nginx
    - edxlocal
    - edxapp
#    - xqueue
#    - xserver
#    - ora
#    - rabbitmq
