- name: Create sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: continuous-integration
    instance_type: m1.large
    security_group: sandbox
    image: ami-d0f89fb9
    region: us-east-1
  tasks:
    - name: Launch instance 
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image wait=true region=$region count=2
      register: ec2
    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=launched 
      with_items: ${ec2.instances}
    - name: Wait for SSH to come up
      local_action: wait_for host=${item.public_dns_name} port=22 delay=60 timeout=320 state=started
      with_items: ${ec2.instances}

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"
  tasks:
    command: true


- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      local_action: 
        module: ec2 
        termination_list: ${ec2.instances}
#      with_items: ${ec2.instances}
