- name: Create sandbox instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: continuous-integration
    instance_type: m1.small
    security_group: sandbox
    image: ami-d0f89fb9
    region: us-east-1
  roles:
    - launch_instance

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
    

- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      local_action: 
        module: ec2 
        termination_list: ${ec2.instances}
#      with_items: ${ec2.instances}
