- name: Configure instance(s)
  hosts: edx_gce
  sudo: True
  gather_facts: True
  vars:
    migrate_db: True
    mysql5_workaround: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
