- hosts: tag_Group_edxapp_custom
  vars_files:
  # using conditional loading to override defaults for site-specific installs
    - "{{ secure_dir }}/edxapp_stage_vars.yml"
    - "{{ secure_dir }}/edxapp_custom_vars.yml"
    - "{{ secure_dir }}/users.yml"
    - "{{ secure_dir }}/edxapp_stage_users.yml"
  roles:
    - common
    - nginx
    - lms
