- hosts: security_group_edx-app-stage2-EdxappServerSecurityGroup-1H8VM8XQZSPZT
  vars_files:
    - ["{{ secure_file_dir }}/edxapp_stage_vars.yml", "vars/secure_default/edxapp_stage_vars.yml"]
    - ["{{ secure_file_dir }}/users.yml", "vars/secure_default/users.yml"]
    - ["{{ secure_file_dir }}/edxapp_stage_users.yml", "vars/secure_default/edxapp_stage_users.yml"]
  roles:
    - common
    - nginx
    - lms
