---
# Provisions a gerrit review server on EC2.  Note that a postgres RDS instance 
# must be manually created before running this script.  The details for the database
# must be populated in the secure variables.  The DB security group for the RDS
# instance will be modified to point to the provisioned instance.
#
# Usage:
#   ansible-playbook gerrit-provision.yml -e "@/path/to/secure/vars/gerrit.yml"

- name: Provision gerrit review server instance
  hosts: localhost
  gather_facts: False
  vars:
    instance_type: m1.medium
    region: us-east-1
    image: ami-a73264ce
    security_group_name: Gerrit
    rds_security_group_name: gerritdb
    request_token: gerrit2
  tasks:
    - name: security group created
      local_action:
        module: ec2_group
        name: "{{ security_group_name }}"
        description: "A gerrit review server"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 29418
            to_port: 29418
            cidr_ip: 0.0.0.0/0
      register: security

    - name: launch instance
      local_action:
        module: ec2
        key_name: "{{ gerrit_provision_keypair_name }}"
        group_id: "{{ security.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        count: 1
        region: "{{ region }}"
        wait: yes
        id: "{{ request_token }}"
        instance_tags: '{ "Name": "gerrit" }'
      register: ec2

    - name: domain name assigned
      local_action:
        module: route53
        command: create
        overwrite: yes
        zone: "{{ gerrit_route53_zone }}"
        type: CNAME
        ttl: 300
        record: "{{ gerrit_hostname }}"
        value: "{{ item.public_dns_name }}"
      with_items: ec2.instances

    - name: added to RDS security group
      local_action:
        module: rds_group
        name: "{{ rds_security_group_name }}"
        description: "A gerrit review server database"
        region: "{{ region }}"
        rules:
          - group_id: "{{ security.group_id }}"

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=gerrit ansible_ssh_user=ubuntu
      with_items: ec2.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 timeout=380 state=started
      with_items: ec2.instances

- name: Setup instance
  hosts: gerrit
  sudo: True
  gather_facts: True
  pre_tasks:
    - name: update apt
      apt: update_cache=yes
  roles:
    - gerrit
