# Configure a Jenkins worker instance
# This has all the requirements to run test jobs,
# but not the Jenkins Java app.

- name: Configure instance(s)
  hosts: jenkins_worker
  sudo: True
  gather_facts: True
  roles:
    - role: rbenv
      rbenv_user: "{{ jenkins_user }}"
      rbenv_user_home: "{{ jenkins_user_home }}"
      rbenv_ruby_version: "{{ jenkins_ruby_version }}"
    - jenkins_worker
