- hosts: tag_Group_discern_stage
  vars_files:
    - ["{{ secure_dir }}/vars/discern_stage_vars.yml"]
    - ["{{ secure_dir }}/vars/users.yml"]
    - ["{{ secure_dir }}/vars/discern_stage_users.yml"]
  roles:
    - common
    - discern
