- hosts:
    - tag_Group_mlapi_dev
  vars_files:
    - "{{ secure_dir }}/vars/mlapi_dev_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/mlapi_dev_users.yml"
  roles:
    - common
    - discern
  sudo: True
- hosts:
    - tag_Group_mlapi-rabbitmq_dev
  vars_files:
    - "{{ secure_dir }}/vars/mlapi_dev_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/mlapi_dev_users.yml"
  roles:
    - common
    - rabbitmq
  sudo: True
- hosts:
    - tag_Group_mlapi-bastion_dev
  vars_files:
    - "{{ secure_dir }}/vars/mlapi_dev_vars.yml"
    - "{{ secure_dir }}/vars/users.yml"
    - "{{ secure_dir }}/vars/mlapi_dev_users.yml"
  roles:
    - common
  sudo: True

