- hosts:
    - tag_Group_mlapi_sandbox
  vars_files:
    - ["{{ secure_dir }}/vars/discern_sandbox_vars.yml"]
    - ["{{ secure_dir }}/vars/users.yml"]
    - ["{{ secure_dir }}/vars/discern_sandbox_users.yml"]
  roles:
    - common
    - discern
