- hosts: tag_Name_edx-tst1
  sudo: yes
  user: ubuntu
  tasks:
    - user: name=jarv comment="John Jarvis"
    - action: file dest=/home/jarv/.ssh state=directory
    - copy:
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHv6xeLcSBJfMwKKNvFry39aewwu8Mim/ZDCTMe5KQIAajuEQfsnlzOG2mmnyIAn8TcW6VnT5z0dDffK/6ZGpiW9xRREpy40+vuP/bd2kuAiTyvLn1F6qKPrfIQhTYJrrvg2c1K9NSeu8rwQaZc3ApXC55GAmyY+fP4RTL5c6GMC/LiaMo0nvsPDdAxZVrkvc+0VK6QQiLz0LJc0W7KrtOUpcqzrye7z8FLbWcIAgKoAUdpGNs9TPNL/gy8H8ArwjW7zSfrvH8NAiLUtI/brNobC7vPoo6MkQgpGcFbOKJUYMhFP6KrEJqv99EQXlf9NKfQcaFoC55oIzKdQHzAZTz jarv@madison
        dest: /home/jarv/.ssh/authorized_keys
