- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
  vars_files:
    - "group_vars/all"
  roles:
    - common
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
      - xserver
      - xqueue
    - edxlocal
    - supervisor
    - mongo
    - edxapp
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - { role: 'edxapp', celery_worker: True }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - xserver
