- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    jenkins_user: "vagrant"
    jenkins_group: "vagrant"
    jenkins_user_home: "/home/vagrant"
  vars_files:
    - "group_vars/all"
  roles:
    - common
    - edxlocal
    - edxapp
    - jenkins_worker_browser
