---
- name: Install Firefox
  apt: pkg=firefox

- name: Download PhantomJS
  get_url: url={{ jenkins_phantomjs_url }}
           dest=/var/tmp/{{ jenkins_phantomjs_archive }}

- name: Untar PhantomJS
  command: tar -xjf /var/tmp/{{ jenkins_phantomjs_archive }} -C /var/tmp/
           creates=/var/tmp/{{ jenkins_phantomjs_folder }}

- name: Install PhantomJS
  command: mv /var/tmp/{{ jenkins_phantomjs_folder }} /usr/local/bin/phantomjs
           creates=/usr/local/bin/phantomjs

- name: Set PhantomJS permissions
  file: path=/usr/local/bin/phantomjs mode=0755 state=directory

- name: Install chrome dependencies
  apt: pkg=libgconf2-4,libxss1,libnss3-1d,libcurl3,xdg-utils

- name: Install unzip O_o
  apt: pkg=unzip

- name: Install Google Chrome
  get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb dest=/var/tmp/google-chrome-stable_current_amd64.deb

- name: Install Google Chrome 2
  command: dpkg -i google-chrome-stable_current_amd64.deb
           chdir=/var/tmp
  ignore_errors: True

- name: Install ChromeDriver
  get_url: url=https://chromedriver.googlecode.com/files/chromedriver_linux64_2.1.zip dest=/var/tmp/chromedriver_linux64_2.1.zip

- name: Install ChromeDriver 2
  shell: unzip /var/tmp/chromedriver_linux64_2.1.zip
         chdir=/var/tmp

- name: Install ChromeDriver 3
  shell: mv /var/tmp/chromedriver /usr/local/bin/chromedriver

- name: Install Chromedriver 4
  file: path=/usr/local/bin/chromedriver mode=0755

