---
- name: Install Jenkins
  shell: wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Install Jenkins 2
  shell: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Install Jenkins 3
  shell: apt-get update

- name: install jenkins 4
  apt: pkg=jenkins state=present

- name: Make plugins directory
  shell: mkdir -p {{ jenkins_home }}/plugins

- name: Mod plugins directory permissions
  shell: chmod -R 777 {{ jenkins_home }}/plugins

- name: Install Jenkins plugins
  get_url: url=http://updates.jenkins-ci.org/latest/${item}
           dest={{ jenkins_home }}/plugins/${item}
  with_items:
    - ant.hpi
    - backup.hpi
    - build-name-setter.hpi
    - build-timeout.hpi
    - cobertura.hpi
    - credentials.hpi
    - cvs.hpi
    - dashboard-view.hpi
    - external-monitor-job.hpi
    - ghprb.hpi
    - git.hpi
    - github.hpi
    - git-client.hpi
    - github-api.hpi
    - github-oauth.hpi
    - git-notes.hpi
    - htmlpublisher.hpi
    - javadoc.hpi
    - jobConfigHistory.hpi
    - ldap.hpi
    - mailer.hpi
    # - maven-plugin.hpi
    - mercurial.hpi
    - nested-view.hpi
    - next-build-number.hpi
    - notification.hpi
    - pam-auth.hpi
    - parameterized-trigger.hpi
    - postbuild-task.hpi
    - rbenv.hpi
    - ruby-runtime.hpi
    - shiningpanda.hpi
    - ssh-credentials.hpi
    - ssh-slaves.hpi
    - subversion.hpi
    - thinBackup.hpi
    # - timestamper.hpi
    - tmpcleaner.hpi
    - token-macro.hpi
    - translation.hpi
    - violations.hpi
  notify:
    - restart Jenkins

- name: Mod plugins directory permissions (Again)
  shell: chmod -R 777 {{ jenkins_home }}/plugins

- name: Restart Jenkins to allow for new plugins
  shell: service jenkins restart

- name: Make backup directory
  shell: mkdir {{ jenkins_home }}/backup

- name: Make backup directory
  shell: chmod -R 777 {{ jenkins_home }}/backup

- name: Chmod mnt
  shell: chmod -R 777 /mnt/

- name: Chmod /usr/local
  shell: chmod -R 777 /usr/local/

- name: chmod tmp
  shell: chmod -R 777 /tmp/

- name: Symbolic link site packages
  shell: ln -s /usr/local/lib/python2.7/site-packages/ /usr/local/lib/python2.7/dist-packages/

- name: install numpy
  shell: pip install numpy==1.6.2

- name: install scipy
  shell: pip install scipy==0.11.0

# - name: cmod lib directory for restore **Undo this after restore**
#   shell: chmod -R 777 /var/lib

# - name: Git clone
#   action: git repo=https://github.com/lapentab/jenkinsconfig.git dest={{jenkins_home}}/backup
