---
- name: Symbolic link site packages
  shell: ln -s -f /usr/local/lib/python2.7/site-packages/ /usr/local/lib/python2.7/dist-packages/

- name: install numpy
  shell: pip install numpy==1.6.2

- name: install scipy
  shell: pip install scipy==0.11.0
