# Stop xqueue service.
- name: xqueue | stop xqueue service
  service: name=xqueue state=stopped
  tags:
  - deploy

- name: xqueue | stop xqueue consumer service
  service: name=xqueue_consumer state=stopped
  tags:
  - deploy

- name: xqueue | create xqueue application config
  template: src=xqueue.env.json.j2 dest={{xqueue_app_dir}}/xqueue.env.json mode=0640 owner={{ xqueue_user }} group=adm
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | create xqueue auth file
  template: src=xqueue.auth.json.j2 dest={{xqueue_app_dir}}/xqueue.auth.json mode=0640 owner={{ xqueue_user }} group=adm
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

# Do A Checkout
- name: xqueue | git checkout xqueue repo into {{app_dir}}
  git: dest={{xqueue_code_dir}} repo={{xqueue_source_repo}} version={{xqueue_version}}
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy


# Install the python pre requirements into {{ xqueue_venv_dir }}
- name : install python pre-requirements
  pip: requirements="{{xqueue_pre_requirements_file}}" virtualenv="{{xqueue_venv_dir}}" state=present
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

# Install the python post requirements into {{ xqueue_venv_dir }}
- name : install python post-requirements
  pip: requirements="{{xqueue_post_requirements_file}}" virtualenv="{{xqueue_venv_dir}}" state=present
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | syncdb and migrate
  shell: SERVICE_VARIANT=xqueue {{ xqueue_venv_dir }}/bin/django-admin.py syncdb --migrate --noinput --settings=xqueue.aws_settings --pythonpath=/opt/wwc/xqueue
  when: migrate_db is defined and migrate_db|lower == "yes"
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | create users
  shell: SERVICE_VARIANT=xqueue {{ xqueue_venv_dir }}/bin/django-admin.py update_users --settings=xqueue.aws_settings --pythonpath=/opt/wwc/xqueue
  when: update_users is defined
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | stop xqueue
  service: name=xqueue state=stopped
  tags:
  - deploy

- name: xqueue | start xqueue
  service: name=xqueue state=started
  tags:
  - deploy

- name: xqueue | start xqueue consumer
  service: name=xqueue_consumer state=started
  tags:
  - deploy
