# Stop xqueue service.
- name: xqueue | stop xqueue service
  supervisorctl: >
    name=xqueue
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=stopped
  tags:
  - deploy

- name: xqueue | stop xqueue consumer service
  supervisorctl: >
    name=xqueue_consumer
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=stopped
  tags:
  - deploy

- name: xqueue | create xqueue application config
  template: src=xqueue.env.json.j2 dest={{ xqueue_app_dir }}/xqueue.env.json mode=0644
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | create xqueue auth file
  template: src=xqueue.auth.json.j2 dest={{ xqueue_app_dir }}/xqueue.auth.json mode=0644
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: "xqueue | writing supervisor scripts - xqueue, xqueue consumer"
  template: >
    src={{ item }}.conf.j2 dest={{ supervisor_cfg_dir }}/{{ item }}.conf
    owner={{ supervisor_user }} group={{ common_web_user }} mode=0644
  with_items: ['xqueue', 'xqueue_consumer']
  tags:
  - deploy

- name: xqueue | ensuring xqueue and xqueue_consumer are activated in supervisor
  supervisorctl: >
    name="{{ item }}"
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=present
  with_items: ['xqueue', 'xqueue_consumer']
  tags:
    - deploy

# Do A Checkout
- name: xqueue | git checkout xqueue repo into xqueue_code_dir
  git: dest={{ xqueue_code_dir }} repo={{ xqueue_source_repo }} version={{ xqueue_version }}
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy


# Install the python pre requirements into {{ xqueue_venv_dir }}
- name : install python pre-requirements
  pip: requirements="{{ xqueue_pre_requirements_file }}" virtualenv="{{ xqueue_venv_dir }}" state=present
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

# Install the python post requirements into {{ xqueue_venv_dir }}
- name : install python post-requirements
  pip: requirements="{{ xqueue_post_requirements_file }}" virtualenv="{{ xqueue_venv_dir }}" state=present
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | syncdb and migrate
  shell: >
    SERVICE_VARIANT=xqueue {{ xqueue_venv_bin }}/django-admin.py syncdb --migrate --noinput --settings=xqueue.aws_settings --pythonpath={{ xqueue_code_dir }}
  when: migrate_db is defined and migrate_db|lower == "yes"
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | create users
  shell: >
    SERVICE_VARIANT=xqueue {{ xqueue_venv_bin }}/django-admin.py update_users --settings=xqueue.aws_settings --pythonpath={{ xqueue_code_dir }}
  sudo_user: "{{ xqueue_user }}"
  tags:
  - deploy

- name: xqueue | start xqueue
  supervisorctl: >
    name=xqueue
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=started
  tags:
  - deploy

- name: xqueue | start xqueue consumer
  supervisorctl: >
    name=xqueue_consumer
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=started
  tags:
  - deploy
