# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
# Check out xqueue repo to {{xqueue_code_dir}}
#
#

- name: xqueue | create application user
  user: >
    name="{{ xqueue_user }}"
    home="{{ xqueue_app_dir }}"
    createhome=no
    shell=/bin/false

- name: xqueue | create xqueue app and venv dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ xqueue_user }}"
    group="{{ common_web_group }}"
  with_items:
    - "{{ xqueue_app_dir }}"
    - "{{ xqueue_venvs_dir }}"

- name: xqueue | install a bunch of system packages on which xqueue relies
  apt: pkg={{','.join(xqueue_debian_pkgs)}} state=present
  notify:
  - xqueue | restart xqueue
  - xqueue | restart xqueue consumer


- name: xqueue | create xqueue db
  mysql_db: >
    name={{xqueue_auth_config.DATABASES.default.NAME}}
    login_host={{xqueue_auth_config.DATABASES.default.HOST}}
    login_user={{xqueue_auth_config.DATABASES.default.USER}}
    login_password={{xqueue_auth_config.DATABASES.default.PASSWORD}}
    state=present
    encoding=utf8
  when: xqueue_create_db is defined and xqueue_create_db|lower == "yes"

- name: "xqueue | writing supervisor scripts - xqueue, xqueue consumer"
  template: >
    src={{ item }}.conf.j2 dest={{ supervisor_cfg_dir }}/{{ item }}.conf
    owner={{ supervisor_user }} group={{ common_web_user }} mode=0644
  with_items: ['xqueue', 'xqueue_consumer']
  tags:
  - deploy

- include: deploy.yml

  # call supervisorctl update. this reloads
  # the supervisorctl config and restarts
  # the services if any of the configurations
  # have changed.
  #
  # we don't use notifications for supervisor because
  # they don't work well with parameterized roles.
  # See https://github.com/ansible/ansible/issues/4853
- name: xqueue | update supervisor configuration
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  register: supervisor_update
  changed_when: supervisor_update.stdout != ""

- name: xqueue | create a symlink for venv python
  file: >
    src="{{ xqueue_venv_bin }}/{{ item }}"
    dest={{ COMMON_BIN_DIR }}/{{ item }}.xqueue
    state=link
  with_items:
  - python
  - pip



