# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
- name: create cms application config
  template: src=cms.env.json.j2 dest={{ edxapp_app_dir }}/cms.env.json mode=640 owner={{ edxapp_user }}
  tags:
  - cms-env
  - cms
  - update
  - deploy

- name: create cms auth file
  template: src=cms.auth.json.j2 dest={{ edxapp_app_dir }}/cms.auth.json mode=640 owner={{ edxapp_user }}
  tags:
  - cms-env
  - cms
  - update
  - deploy

- name: Create CMS log target directory
  file: path={{ edxapp_log_dir }}/cms state=directory owner={{ common_log_user }} mode=0750
  tags:
  - cms
  - cms-env
  - logging
  - update
  - deploy

# Creates CMS upstart file
- include: upstart.yml basename=cms
  when: celery_worker is not defined

- include: upstart.yml basename=edx-worker-cms
  when: celery_worker is defined
