# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
- name: create cms application config
  template: >
    src=cms.env.json.j2
    dest={{ edxapp_app_dir }}/cms.env.json
  sudo_user: "{{ edxapp_user }}"
  tags:
  - deploy

- name: create cms auth file
  template: >
    src=cms.auth.json.j2
    dest={{ edxapp_app_dir }}/cms.auth.json
  sudo_user: "{{ edxapp_user }}"
  tags:
  - deploy

# Creates CMS upstart file
- include: upstart.yml basename=cms
  when: celery_worker is not defined

- include: upstart.yml basename=edx-worker-cms
  when: celery_worker is defined
