# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
- name: create lms application config
  template: >
    src=lms-preview.env.json.j2
    dest={{ edxapp_app_dir }}/lms-preview.env.json
  tags:
  - deploy

- name: create lms auth file
  template: >
    src=lms-preview.auth.json.j2
    dest={{ edxapp_app_dir }}/lms-preview.auth.json
  tags:
  - deploy

# Creates LMS Preview upstart file
- include: upstart.yml basename=lms-preview
