# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
- name: create lms application config
  template: >
    src=lms-preview.env.json.j2
    dest={{ edxapp_app_dir }}/lms-preview.env.json
    mode=640
    owner={{ edxapp_user }}
    group={{ common_web_user }}
  tags:
  - deploy

- name: create lms auth file
  template: >
    src=lms-preview.auth.json.j2
    dest={{ edxapp_app_dir }}/lms-preview.auth.json
    mode=640
    owner={{ edxapp_user }}
    group={{ common_web_user }}
  tags:
  - deploy

- name: Create lms-preview log target directory
  file: >
    path={{ edxapp_log_dir }}/lms-preview
    state=directory
    owner={{ common_log_user }}
    mode=0750
  tags:
  - deploy

# Creates LMS Preview upstart file
- include: upstart.yml basename=lms-preview
