---
- name: create lms application config
  template: >
    src=lms.env.json.j2
    dest={{ edxapp_app_dir }}/lms.env.json
  sudo_user: "{{ edxapp_user }}"
  tags:
  - deploy

- name: create lms auth file
  template: >
    src=lms.auth.json.j2
    dest={{ edxapp_app_dir }}/lms.auth.json
  sudo_user: "{{ edxapp_user }}"
  tags:
  - deploy

# Creates LMS upstart file
- include: upstart.yml basename=lms
  when: celery_worker is not defined

- include: upstart.yml basename=edx-worker-lms
  when: celery_worker is defined
