---
- name: create lms application config
  template: src=lms.env.json.j2 dest={{ edxapp_app_dir }}/lms.env.json mode=640 owner={{ edxapp_user }}
  tags:
  - lms
  - lms-env
  - update
  - deploy

- name: create lms auth file
  template: src=lms.auth.json.j2 dest={{ edxapp_app_dir }}/lms.auth.json mode=640 owner={{ edxapp_user }}
  tags:
  - lms
  - lms-env
  - update
  - deploy

- name: Create lms log target directory
  file: path={{ edxapp_log_dir }}/lms state=directory owner=syslog group={{ common_log_user }} mode=2750
  tags:
  - lms
  - lms-env
  - logging
  - update
  - deploy

# Creates LMS upstart file
- include: upstart.yml basename=lms
  when: celery_worker is not defined

- include: upstart.yml basename=edx-worker-lms
  when: celery_worker is defined
