# requires:
#  - group_vars/all
#  - common/tasks/main.yml
---
- name: edxapp | create application user
  user: name="{{ edxapp_user }}"

- name: edxapp | create edxapp app dir
  file: >
    path="{{ item }}"
    state=directory
    owner=root
    group="{{ edxapp_user }}"
  with_items:
    - "{{ edxapp_app_dir }}"
    - "{{ edxapp_venvs_dir }}"

- name: edxapp | create edxapp log dir
  file: >
    path="{{ edxapp_log_dir }}"
    state=directory
    owner=syslog
  notify: common | restart logrotate

- name: edxapp | create edxapp data dirs
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ edxapp_user }}"
  with_items:
    - "{{ edxapp_data_dir }}/staticfiles"
    - "{{ edxapp_data_dir }}/data"
    - "{{ edxapp_data_dir }}/uploads"
    - "{{ edxapp_data_dir }}/themes"

- name: edxapp | install system packages on which LMS and CMS rely
  apt: pkg={{','.join(lms_debian_pkgs)}} state=present

- name: edxapp | creating edxapp upstart script
  sudo: True
  template: src=edxapp.conf.j2 dest=/etc/init/edxapp.conf owner=root group=root
  when: "celery_worker is not defined"

- name: edxapp | create edx-workers upstart script
  template: src=edx-workers.conf.j2 dest=/etc/init/edx-workers.conf owner=root group=root
  when: "celery_worker is defined"

- include: deploy.yml
